### ISSUE TITLE
Very large amount of false positives with rule 932200

### ISSUE THREAD

**Issue by Taiki-San** [coreruleset/coreruleset#1818]
### Description

Rule 932200 is generating very high level of false positives on real world traffic.  
Here are some of the examples I found after running it for a few hours:
- `https://website/bla/grille?jour= 4`
- `<a href='https://newswebsite/article.html'>someone's name</a>`
- `{"$productid":"4242"}`

I have not dug enough to determine if this is a bug in the regex or just a FP prone strategy.
Considering that it triggers a lot (on purpose?) on fairly common patterns, does it belong in PL1?

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
Hi @Taiki-San ,

thank you for reporting this. Unfortunately, I can't reproduce the problem using the three examples you wrote. Can you provide more details about your setup and a log for each test? I got these results:

`https://website/bla/grille?jour= 4`
no rule triggered at PL1

`<a href='https://newswebsite/article.html'>someone's name</a>`
rules triggered at PL1: 941150, 941320, 942260

`{"$productid":"4242"}`
no rule triggered at PL1 (is this sent on request body with content-type application/json?)

**Comment by Taiki-San** [comment]
Hey,

We're running the patterns on their own, based from an import from PL1.
I know that our usage deviate a bit from modsecurity and that in the past, import errors introduced false positives.
However I'm not seeing what could be the issue here.

Recently, rule 932200 was introduced as PL1: https://github.com/coreruleset/coreruleset/blob/c2a7028f8db71c9c2284c7006496cc6dc51a3fd5/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf#L591-L627
The pattern triggers on what I just sent: https://regex101.com/r/AEDV0Y/1/

We're running those rules in a bit of a different context (inside the application, from parsed parameters) so it might be a bit fiddly to reproduce with modsecurity and encoding, hence why I focus on the pattern.

**Comment by theMiddleBlue** [comment]
Hi @Taiki-San 

> The pattern triggers on what I just sent: https://regex101.com/r/AEDV0Y/1/
We're running those rules in a bit of a different context (inside the application, from parsed parameters) so it might be a bit fiddly to reproduce with modsecurity and encoding, hence why I focus on the pattern.
>
> I also would like to make clear that we're not here trying to get free support.
We could fork CRS and tweak/fix patterns based on our data but based on previous chats with @dune73, we understood those reports were useful to the project, even if our setup is slightly different

Thank you. The problem, reading the three payloads you wrote, seems that you just assume that all of them are values of ARGs sent inside the querystring (in URL or inside the request body as a www-form-urlencoded request). We need this kind of information to reproduce your problem (and that's why we created a template for a false-positive issue that asks for a description, audit logs, and information about config/env).

For example, your 3rd payload seems JSON, and if you send it as "application/json" content-type ModSecurity uses a different body processor that parses `$productid` as the ARG_NAME and `4242` as ARG value. That's why I'm asking you for more information about your blocked requests, to understand better how to fix it.

Anyway, based on a message from another user on our slack channel, I've created a new version of 932200 (still in draft) that should address FPs on your third payload if sent as www-form-urlencoded. It would be really helpful if you can give it a try :)

thanks!

**Comment by Taiki-San** [comment]
Thanks for the details @theMiddleBlue, I understand better the friction.
A peculiarity of our usage is that by the time the input reach us, it was already parsed (the application can still do post processing but the framework at least is done). The JSON input is for instance ingested as is by the application (so likely a urlencoded blob).

Because of that, we only have fairly limited visibility on the exact incoming request and all that I can say for sure is that this decoded value triggered this pattern. I can try to reverse engineer the incoming request but it's ultimately a cat and mouse game to trick the modsecurity parser into evaluating the input I had.

A risk we're aware of is that this processing mean that some pattern that are meant to run on the raw input may get confused in our environment. We also reimplemented those operators & transformers ourselves and run on a different regex engine so we expected deviations in the maturity of patterns. This could explain deviations and I'm thus careful not to report false positives we get when our use cases is the most different (running on ARGS with none/few decoding transformers).

Thanks a lot for the experimental regex, I'm checking it out.

**Comment by dune73** [comment]
Any update on this @Taiki-San?

**Comment by franbuehler** [comment]
Do you have any updates on this, @Taiki-San?
In PR #1820 the rule has been fixed and additionally in PR #1831 the rule has been moved to PL2.
We would like to hear your feedback so that we can properly close this issue.

**Comment by Taiki-San** [comment]
Hey, my apologies for the delayed response.
At the time of 1820, our runtime didn't actually support `MATCHED_VAR` but combined with 1831, the issue can be closed on my end.
I'll run more tests in the future and depending of what they show, I'll open a new, more specific issue :)
