### ISSUE TITLE
upgrade-insecure-requests false positive RESPONSE-951-DATA-LEAKAGES-SQL.conf rule 951120

### ISSUE THREAD

**Issue by adrelanos** [coreruleset/coreruleset#1827]
### Audit Logs / Triggered Rule Numbers

```
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i:ORA-[0-9][0-9][0-9][0-9]|java\.sql\.SQLException|Oracle error|Oracle.*Driver|Warning.*oci_.*|Warning.*ora_.*)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html class="client-nojs" lang="en" dir="ltr">\x0a<head>\x0a<meta charset="UTF-8" (217077 characters omitted)' ) [file "/usr/share/coreruleset/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "66"] [id "951120"] [rev ""] [msg "Oracle SQL Information Leakage"] [data "Matched Data: upgrade-insecure-requests found within TX:sql_error_match: 1"] [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-oracle"] [tag "attack-disclosure"] [tag "OWASP_CRS"] [tag "OWASP_CRS/LEAKAGE/ERRORS_SQL"] [tag "CWE-209"] [hostname "redacted"] [uri "/wiki/KVM"] [unique_id "redacted"] [ref "redacted"
```

### Your Environment

* CRS version (e.g., v3.2.0): v3.2.0
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3):  v1.0.1 
* Web Server and version (e.g., apache 2.4.41): nginx
* Operating System and version: Debian

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @adrelanos - thanks for report.

I reviewed your issue, but I think we need more information for final solution.

The rule [951120](https://github.com/coreruleset/coreruleset/blob/be34e996fe19078d5fd07e101af21bef1df59e2c/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf#L66-L89) triggered, because the `sql_error_match` transaction variable had been set up [previously](https://github.com/coreruleset/coreruleset/blob/be34e996fe19078d5fd07e101af21bef1df59e2c/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf#L39) in rule [951100](https://github.com/coreruleset/coreruleset/blob/be34e996fe19078d5fd07e101af21bef1df59e2c/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf#L28-L39).

951100 checks the whole `RESPONSE_BODY` with operator `@pmFromFile` against the file [sql-errors.data](https://github.com/coreruleset/coreruleset/blob/v3.2/master/rules/sql-errors.data).

Your included log message contains an interesting part:
```
[data "Matched Data: upgrade-insecure-requests found within TX:sql_error_match: 1"]
```
but the `sql_errors.data` file **doesn't** contain this pattern (namely: 'upgrade-insecure-requests'), so first we have to figure out, why this rule triggered.

If the response is public, please share it with us here - otherwise, please send it to security@coreruleset.org, or directly to me (you can find my address under my profile). It would good to see the whole response, including headers.

Finally a good advise: the 3.0.2 is a bit old, it's very important to upgrade to 3.0.4 - or even better to get the current master branch.

**Comment by airween** [comment]
Hi @adrelanos,

if this problem still exists, please collect the affected response headers and body in a pack, and let us know for further inquiry.

**Comment by airween** [comment]
Without detailed information I'm going to close this issue.

Feel free to re-open, if you still need to solve it - but we need more information.
