### ISSUE TITLE
Bring back OWASP_CRS/FOO/BAR tags

### ISSUE THREAD

**Issue by fabian-hahn** [coreruleset/coreruleset#1860]
### Motivation

We have set up dozens of SecRuleRemoveByTag "OWASP_CRS/\*/\*" exceptions. They seemed the best way to address special cases for our sites and are readable w/o knowing rule#.  We were under the assumption, these tags would be more stable than the msg or id to address individual rules.

This will keep us from upgrading to CRS 3.3.0

### Proposed solution

Add OWASP_CRS/FOO/BAR-style descriptive tags to all rules.

### Alternatives

The CAPEC codes are not specific enough to address FPs.  iE. tag "capec/1000/210/272" will disable many useful rules beyond 920440.

### Additional context

  SecRuleRemoveByTag "EXT_RESTRICTED"          #  OWASP_CRS 3.2.0
  SecRuleRemoveByTag "capec/1000/210/272"      #  OWASP_CRS 3.3.0

**Comment by dune73** [comment]
Hello @fabian-hahn. Thank you for reporting and very, very sorry for your problems.

When we made the step from CRS2 to CRS3 we rearranged the complete rule id namespace - and we promised we would stick to these rule ids now. It's been a couple of years and it's still working nicely.

We've been aware that the tagging has been a mess for year and the cleanup was due / overdue. So we finally implemented this. I am still not entirely happy with the tagging for exactly the problem you describe.

There are now three types of tags. The ones that identify CRS, the tags that identify an application / language / etc. and then the ones that identify an attack pattern - CAPEC that is. The 2nd category is not granular enough brings about the problem you describe. Removing rules based on the CAPEC tag is not meant to work and it's a bad practice as you realized yourself.

So the best approach for what you have in mind is doing exclusions on rule IDs / groups of rule IDs. I'm sorry to say that you set your bet on the wrong horse: rule IDs were meant to be more stable than the tags and tags are only stabilizing now.

A reasonable question is why we removed the old tags instead of running in parallel. The problem is that the space in the rule alert message is scarce and ModSec will cut the tags (which leads to a malformed alert message!)

As a  bit of a remedy, I am currently writing a blog post that explains how I went about to retag all the rules with a script. The blog post is going to be a good base for you to bring back the tags for your installation or help you with the transition (like transforming tag-based rule exclusions into id based rule exclusions).

**Comment by fabian-hahn** [comment]
Christian,
   thank you for your explanation.  This makes sense.  We were not aware that the rule ids were promised to be stable over long releases of the rule-set.    

  We have been using OWASP_CRS in different projects to improve web-site security.   We are very happy with the excelent foundation you have provided.  

  May I suggest, from our experience in using the set over the years, that "speaking" names might ease the discussion between parties involved.    Security is a tough issue as it is, we should make the participation accessible and intuitive as possible.  Speaking for me, during definition sessions I find the tag-string approach easier to discuss than remembering the ids.  These tags have also helped a lot in finding root causes in the output.   I am not sure the CAPAC codes will assist in a similar way.

  Looking forward to read your blog post about this.

  Many thanks for your consideration.  Fabian

**Comment by dune73** [comment]
I agree with you that speaking names would be better. Unfortunately, ModSec does not do alphanumeric IDs. But we are looking into ways to improve the documentation / make it more accessible and easier to integrate.

CAPEC tags are meant for reporting, not necessarily as a communication tool.

And thank you for the kind words. Glad you like our rules.

What organisation are you working for, if I may ask? (DM welcome: folini@netnea.com)
