### ISSUE TITLE
PGP SIGNED MESSAGE content gets flagged

### ISSUE THREAD

**Issue by rednoah** [coreruleset/coreruleset#1874]
### Description

My service accepts `PGP SIGNED MESSAGE` text files to be uploaded via `HTTP POST`. Looks like the `\r\n` required by PGP ascii armored file specification gets flagged. The digital signature part also seems to get flagged somehow.

### Audit Logs / Triggered Rule Numbers

```
[Fri Sep 04 05:06:51.532088 2020] [:error] [pid 21278] [client IP:PORT] [client IP] ModSecurity: Warning. Pattern match "[\\\\n\\\\r]" at ARGS_NAMES:-----BEGIN PGP SIGNED MESSAGE-----\\r\\nHash: SHA512\\r\\n\\r\\nProduct: FileBot\\r\\nNAME: adam\\r\\nEmail: EMAIL\\r\\nOrder: P17245884\\r\\nIssue-Date: 2020-08-26\\r\\nValid-Until: 2021-09-02\\r\\n-----BEGIN PGP SIGNATURE-----\\r\\n\\r\\niQEzBAEBCgAdFiEEc1MV/TP2QOyyCr5UyhKNCCTOINkFAl9GZeEACgkQyhKNCCTO\\r\\nINl eAf/bRZ8hwNds8tPaPOWTWXdYS1PrEnGCvuDWlb07NV14JlhuqL7JQaDJ9KH\\r\\nFeiUzDG/JbncmBIRRFVG rGdMBmt8OCnj1yW8QardcHvBz/5A4NOIUZweijFejvb\\r\\n8NDXZ4NxU4BrbGGROG7OLW/R26ELLpgBuLZbG5/NDD6R/QEJmBnvNtUfMOBEn64I\\r\\n6nNqO4WH3cVq4qSv/ApVU/Iek8vXbXHE/nC/A8lcX8pphyLV9nCEST3XeqgjR0HP\\r\\n696Po qyH3XPzDrDRZ1JdqsxF5HDFSHlmcDY0OCl7e8 ekXuTg1wA3m975Adyqis\\r\\n3LPWsdKTuBdbuK LwJmZHbIt01WbKg. [file "/dh/apache2/template/etc/mod_sec3_CRS/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "171"] [id "921150"] [msg "HTTP Header Injection Attack via payload (CR/LF detected)"] [data "Matched Data: \\x0d found within ARGS_NAMES:-----BEGIN PGP SIGNED MESSAGE-----\\x5cr\\x5cnHash: SHA512\\x5cr\\x5cn\\x5cr\\x5cnProduct [hostNAME "HOST"] [uri "/verify/P17245884"] [unique_id "X1It2@kyOZuAIv3a6OjZ0gAAAAs"]
[Fri Sep 04 05:06:51.533329 2020] [:error] [pid 21278] [client IP:PORT] [client IP] ModSecurity: Warning. Pattern match "(?i)(?:;|\\\\{|\\\\||\\\\|\\\\||&|&&|\\\\n|\\\\r|`)\\\\s*[\\\\(,@\\\\'\\"\\\\s]*(?:[\\\\w'\\"\\\\./]+/|[\\\\\\\\'\\"\\\\^]*\\\\w[\\\\\\\\'\\"\\\\^]*:.*\\\\\\\\|[\\\\^\\\\.\\\\w '\\"/\\\\\\\\]*\\\\\\\\)?[\\"\\\\^]*(?:m[\\"\\\\^]*(?:y[\\"\\\\^]*s[\\"\\\\^]*q[\\"\\\\^]*l(?:[\\"\\\\^]*(?:d[\\"\\\\^]*u[\\"\\\\^]*m[\\"\\\\^]*p(?:[\\"\\\\^]*s[\\"\\\\^ ..." at ARGS_NAMES:-----BEGIN PGP SIGNED MESSAGE-----\\r\\nHash: SHA512\\r\\n\\r\\nProduct: FileBot\\r\\nNAME: adam\\r\\nEmail: EMAIL\\r\\nOrder: P17245884\\r\\nIssue-Date: 2020-08-26\\r\\nValid-Until: 2021-09-02\\r\\n-----BEGIN PGP SIGNATURE-----\\r\\n\\r\\niQEzBAEBCgAdFiEEc1MV/TP2QOyyCr5UyhKNCCTOINkFAl9GZeEACgkQyhKNCCTO\\r\\nINl eAf/bRZ8hwNds8tPaPOWTWXdYS1PrEnGCvuDWlb07NV14JlhuqL7JQaDJ9KH\\r\\nFeiUzDG/JbncmBIRRFVG rGdMBmt8OCnj1yW8QardcHvBz/5A4NOIUZweijFejvb\\r\\n8NDXZ4NxU4BrbGGROG7OLW/R26ELLpgBuLZbG5/NDD6R/QEJmBnvNtUfMOBEn64I\\r\\n6nNqO4WH3cVq4qSv/ApVU/Iek8vXbXHE/nC/A8lcX8pphyLV9nCEST3XeqgjR0HP\\r\\n696Po qyH3XPzDrDRZ1JdqsxF5HDFSHlmcDY0OCl7e8 ekXuTg1wA3m975Adyqis\\r\\n3LPWsdKTuBdbuK LwJmZHbIt01WbKg. [file "/dh/apache2/template/etc/mod_sec3_CRS/REQUEST-932-A [hostNAME "HOST"] [uri "/verify/P17245884"] [unique_id "X1It2@kyOZuAIv3a6OjZ0gAAAAs"]
[Fri Sep 04 05:06:51.538980 2020] [:error] [pid 21278] [client IP:PORT] [client IP] ModSecurity: Access denied with code 418 (phase 2). Operator GE matched 7 at TX:anomaly_score. [file "/dh/apache2/template/etc/mod_sec3_CRS/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "91"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [severity "CRITICAL"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostNAME "HOST"] [uri "/verify/P17245884"] [unique_id "X1It2@kyOZuAIv3a6OjZ0gAAAAs"]
[Fri Sep 04 05:06:51.544745 2020] [:error] [pid 21278] [client IP:PORT] [client IP] ModSecurity: Warning. Operator GE matched 7 at TX:inbound_anomaly_score. [file "/dh/apache2/template/etc/mod_sec3_CRS/RESPONSE-980-CORRELATION.conf"] [line "86"] [id "980130"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 10 - SQLI=0,XSS=0,RFI=0,LFI=0,RCE=5,PHPI=0,HTTP=5,SESS=0): individual paranoia level scores: 10, 0, 0, 0"] [tag "event-correlation"] [hostNAME "HOST"] [uri "/verify/P17245884"] [unique_id "X1It2@kyOZuAIv3a6OjZ0gAAAAs"]
```

### Your Environment

Shared hosting environment via Dreamhost.

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by fancsali** [comment]
I am perhaps flogging a dead horse here, but I just stumbled upon the same issue today:

```
[Wed May 05 20:25:47.244247 2021] [:error] [pid 27595] [client 185.220.102.253:5444] [client 185.220.102.253] ModSecurity: Warning. detected SQLi using libinjection with fingerprint 'Tnnof' [file "/usr/share/modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "65"] [id "942100"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: Tnnof found within ARGS:_pgpmime: -----BEGIN PGP MESSAGE-----\\x0d\\x0aVersion: Mailvelope v4.4.0\\x0d\\x0aComment: https://www.mailvelope.com\\x0d\\x0a\\x0d\\x0awcFMAxs0FKK/urYEARAAonF/6j223xLoV1M8Z19wDIjZi4U8pzN+fu1Ptiwj\\x0d\\x0aKZBkprlBefI1NCuNxzSIqBex0o3ELfKDdcrEuu/arxIDDNi0A3ENqnGX6o7f\\x0d\\x0a3oenPN0+NkHJMpPliwqG9FLSUBHhqXR8fBGChABlIgvZMj3ual10J38IIV/C\\x0d\\x0aO9wnluGcmB8JCVLEt1zMNsMrd1jnJYMjbpxECA4xVuCls31y+UdZ+eR9AQv8\\x0d\\x0aTBdAYb+ov/sHyr0oKzSnimvXogtrGPxued2wjm5W2TYXvz3Ce37YEu2+PzgM\\x0d\\x0aM..."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [hostname "my.server.name"] [uri "/"] [unique_id "YJLxO9f-0ksOQjfsPT2IUgAAAA0"], referer: https://my.server.name/
[Wed May 05 20:25:47.253710 2021] [:error] [pid 27595] [client 185.220.102.253:5444] [client 185.220.102.253] ModSecurity: Warning. detected SQLi using libinjection with fingerprint 'Tnnof' [file "/usr/share/modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "65"] [id "942100"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: Tnnof found within ARGS:_pgpmime: -----BEGIN PGP MESSAGE-----\\x0d\\x0aVersion: Mailvelope v4.4.0\\x0d\\x0aComment: https://www.mailvelope.com\\x0d\\x0a\\x0d\\x0awcFMAxs0FKK/urYEARAAonF/6j223xLoV1M8Z19wDIjZi4U8pzN fu1Ptiwj\\x0d\\x0aKZBkprlBefI1NCuNxzSIqBex0o3ELfKDdcrEuu/arxIDDNi0A3ENqnGX6o7f\\x0d\\x0a3oenPN0 NkHJMpPliwqG9FLSUBHhqXR8fBGChABlIgvZMj3ual10J38IIV/C\\x0d\\x0aO9wnluGcmB8JCVLEt1zMNsMrd1jnJYMjbpxECA4xVuCls31y UdZ eR9AQv8\\x0d\\x0aTBdAYb ov/sHyr0oKzSnimvXogtrGPxued2wjm5W2TYXvz3Ce37YEu2 PzgM\\x0d\\x0aM..."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/248/66"] [tag "PCI/6.5.2"] [hostname "my.server.name"] [uri "/"] [unique_id "YJLxO9f-0ksOQjfsPT2IUgAAAA0"], referer: https://my.server.name/
[Wed May 05 20:25:47.263256 2021] [:error] [pid 27595] [client 185.220.102.253:5444] [client 185.220.102.253] ModSecurity: Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomaly_score. [file "/usr/share/modsecurity-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "93"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 10)"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "my.server.name"] [uri "/"] [unique_id "YJLxO9f-0ksOQjfsPT2IUgAAAA0"], referer: https://my.server.name/
[Wed May 05 20:25:47.267285 2021] [:error] [pid 27595] [client 185.220.102.253:5444] [client 185.220.102.253] ModSecurity: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/usr/share/modsecurity-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "91"] [id "980130"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 10 - SQLI=10,XSS=0,RFI=0,LFI=0,RCE=0,PHPI=0,HTTP=0,SESS=0): individual paranoia level scores: 10, 0, 0, 0"] [ver "OWASP_CRS/3.3.0"] [tag "event-correlation"] [hostname "my.server.name"] [uri "/"] [unique_id "YJLxO9f-0ksOQjfsPT2IUgAAAA0"], referer: https://my.server.name/
```

Server is running Debian 10.9 (buster) with with mod-security 2.9.3-1, using CRS 3.3.0-1~bpo10+1.

I was trying to make RoundCube and Mailvelope to play along nicely, if that is of interest to anyone.

**Comment by dune73** [comment]
Thank you for reporting @fancsali, even if it looks like a dead horse. 

In fact having the bot close issues nobody cares about is very sad, yet the situation (and the number of open issues) improved since this has been closed. So let's breath some life into this issue and call on the dev-on-duty @franbuehler to take a first look.

**Comment by airween** [comment]
About a half year ago I have started to work on an exclusion package for Roundcube. I had to hang up the work, but I hope I can pick it up in the near future, so I'm going to assign this issue for myself.

**Comment by azurit** [comment]
I have few rules for Roundcube, i can help with it.

**Comment by dune73** [comment]
Any update here @airween?

**Comment by airween** [comment]
Not yet. I hope I can focus to that in this month.

**Comment by dune73** [comment]
Thank you.

**Comment by airween** [comment]
Hi @rednoah,

can you help me to reproduce this issue?

I reviewed your attached logs, but this part of the first line is a bit strange:
```
ARGS_NAMES:-----BEGIN PGP SIGNED MESSAGE---...
```
Looks like you send a request where the name of an argument is the file?

A `curl` example would be fine.

If I understand you correctly, there is no any connection between RoundCube webmail and this request, right?

**Comment by rednoah** [comment]
It's been a long time, but I'm pretty sure it was something simple like this:
```
curl --data-binary "@/path/to/signed-message.txt" https://server/endpoint
```
Just posting a text file directly, not form-encoded.

The signed message text would have been generated with `gpg --clearsign` but as I remember it wasn't always blocked, presumably because the random digital signature part just sometimes matched something that pushed the score over the limit.
https://www.gnupg.org/gph/en/manual/x135.html

**Comment by airween** [comment]
Thanks @rednoah,

okay, I got it. Now I can take a look this issue.

**Comment by airween** [comment]
Hi @rednoah,

thanks again for the quick `curl` tip, I could reproduce your issue.

I think these are not false positives, the engine with the rule set does what it has to do.

You didn't mention what CRS version you are using, so in my dev environment I checked your request against v3.4/dev. This is just relevant because the links below have generated based on this version's URL's. [This](https://gist.github.com/airween/eb4d4780e71b4eff7eb4cb691e4f2413) is a small script what I used (it helps to find the rule as quickly). (If you want to test it, don't forget to replace the `BASEH` variable at the top of the code.)

I'm using CRS in that environment on PL4, with `SecRuleEngine DetectOnly`. This means the given `curl` command triggered all available rules, because the request will not blocked after the first match. With this setting, I discovered these rules in my log:

[920272](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1379) Invalid character in request (outside of printable chars below ascii 127)
[920273](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1557) Invalid character in request (outside of very strict set)
[920360](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L842) Argument name too long
[921150](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-921-PROTOCOL-ATTACK.conf#L172) HTTP Header Injection Attack via payload (CR/LF detected)
[942430](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1223) Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)
[942431](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1473) Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
[942432](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1649) Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)
[942440](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1267) SQL Comment Sequence Detected
[942460](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L1503) Meta-Character Anomaly Detection Alert - Repetitive Non-Word Characters
[949110](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-949-BLOCKING-EVALUATION.conf#L151) Inbound Anomaly Score Exceeded (Total Score: 68)
[980130](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/RESPONSE-980-CORRELATION.conf#L88) Inbound Anomaly Score Exceeded (Total Inbound Score: 68 - SQLI=28,XSS=0,RFI=0,LFI=0,RCE=0,PHPI=0,HTTP=5,SESS=0): individual paranoia level scores: 10, 13, 24, 21

I think the solution in your case should be to make an exclusion. After I checked the matched variables in these rules above, I've created this exclusion:

```
SecRule REQUEST_URI "@beginsWith /verify/P17245884" \
    "id:1001,\
    phase:1,\
    pass,\
    t:none,\
    log,\
    msg:'Exclusion activated',\
    ctl:ruleRemoveTargetById=920272;ARGS,\
    ctl:ruleRemoveTargetById=920272;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=920272;REQUEST_BODY,\
    ctl:ruleRemoveTargetById=920273;ARGS,\
    ctl:ruleRemoveTargetById=920273;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=920273;REQUEST_BODY,\
    ctl:ruleRemoveById=920360,\
    ctl:ruleRemoveTargetById=921150;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=942430;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=942431;ARGS,\
    ctl:ruleRemoveTargetById=942431;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=942432;ARGS,\
    ctl:ruleRemoveTargetById=942432;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=942440;ARGS,\
    ctl:ruleRemoveTargetById=942440;ARGS_NAMES,\
    ctl:ruleRemoveTargetById=942460;ARGS,\
    ctl:ruleRemoveTargetById=942460;ARGS_NAMES"

```
This solved the problem, and the request didn't trigger any rule.

Put this rule into your `/dh/apache2/template/etc/mod_sec3_CRS/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf`, and check again.

**Comment by airween** [comment]
Hi @rednoah,

did this solve your problem? If yes, pleas close this issue.

**Comment by dune73** [comment]
We have not heard from @rednoah anymore. Closing this issue.
