### ISSUE TITLE
Website defaced 

### ISSUE THREAD

**Issue by albgen** [coreruleset/coreruleset#1937]
hello,

I have a website called https://unemundem.al and on 23rd of november
it has been defaced by the ip 95.181.172.134

Basically the attacker has been able to perform a sql injection on the
wordpress installed and the website was forwarding to another
location.
On wp_options table it has change the values of home and site url to
the follwing url
https://port.lovegreenpencils.ga/det.php?pit=222&sid=5&yuid=243634&

 I have restored it but i'm sure it will try again.
you can find the log from  mod_sec here https://pastebin.pl/view/raw/842d1d82
and it seems this kind of attack is not handled very well 

can you please advice?

thank you

**Comment by theMiddleBlue** [comment]
Hi @albgen 

Is not the first time that I see this technique on WordPress. Reading your logs it seems that your Nginx reply always with 403 Forbidden for each attempt except for the first log. As you can see, in the first log, Nginx reply with 500 but the request seems to come from the authenticated user "bbamiokjopu" (am I correct?). Is it possible that someone has guessed the password of bbamiokjopu via a brute-force attack and then replaced your front page?

>  it seems this kind of attack is not handled very well

In your logs I don't see any response different than 403 or 500, am I wrong? I think that we should see a different response from your Nginx on a successful SQLi attack.

Could you please provides more information about your modsecurity configuration and CRS version and configuration?

I'm going to close this issue just because it seems not related to a specific CRS problem, but please give me more information to understand better what happened.

**Comment by albgen** [comment]
Hi MiddleBlue,

yes that user exists and was also an administrator but i have not created it. Most probably is a user that the attacker has created. I have deleted it.

I think that also the audit log has not recorded the requests that has caused the issues...

The version of modsec is the latest one from the main branch and the nginx is the 1.19.4.
The crs ruleset is the one from https://github.com/SpiderLabs/owasp-modsecurity-crs.git


thank you
the server is a centos 7 vps always updated...

if you need other info let me know. Maybe the log for the website on that precise moment?

**Comment by theMiddleBlue** [comment]
Hi @albgen 

the log could be useful and if you want I can give it a look. It's better to not make them public in this issue, can you send them to themiddle@rev3rse.it ? Also, have you got a list of all WordPress plugins+versions active on your website?
