### ISSUE TITLE
Make Nextcloud ex. rules package more 'tight'

### ISSUE THREAD

**Issue by azurit** [coreruleset/coreruleset#1947]
### Motivation

Exclusion rules package for Nextcloud contains rules with too wide effect - most of them are maching only URL with common file names like `index.php` or `remote.php`. Also, lots of rules are using `@contains` instead of `@endswith`, `@startswith` or proper use of `@rx`.

Rules with most visible problems:
9003130 - matching URLs containing '/index.php/' without any other check and allowing all possible HTTP methods (also includes HTTP method 'jsonp' in lowercase, is this ok?)
9003100 - matching `@contains /remote.php/webdav` without any other check and disabling lots of rules

I understand that exclusion packages should be enabled only for sites running given software but i believe they should be written to not create such big holes in the firewall for other software.

**Comment by franbuehler** [comment]
Hi @azurit, 
I think this is a good idea that we should pursue.
Big holes in the firewall are bad ;-)
Who of us has Nextcloud know-how and could help us with the evaluation and possibly with the implementation of this issue?
I will link this issue in the next issue chat, then we can discuss this and maybe assign it. 
I'll remove the stale issue label.

**Comment by lifeforms** [comment]
Chat decision: Azurit and I will try to work with the Nextcloud community on updating and expanding our exclusion set. Perhaps it will be largely a rewrite, especially cause there have been big changes to the URL structure. Due to my availability constraints, this project will happen in June. We will close this issue and create a new issue about the Nextcloud 'next generation' exclusion project.

**Comment by dune73** [comment]
The issue #1197 has been closed in favor of said Nextcloud "next generation" project. Please do not forget #1197.
