### ISSUE TITLE
how to visualize the modsec audit log 

### ISSUE THREAD

**Issue by ashishkpal** [coreruleset/coreruleset#2040]
hi,

i want to visualize the modsecurity audit logs i have tried from various blog and other thing but couldn't succeeded on this. please help on the same 

i have inhouse ELK server if there is any possibility to push this logs to ELK server

**Comment by dune73** [comment]
Hey @ashishkpal,

This is a tough problem due to the format of the audit-log. I assume you are looking at the concurrent log format with the file tree. The easiest would be to return to serial and centralize that. Otherwise I have seen people buffer it locally or rsync and then grab it, but nothing is documented online.

You may want to ask on the ModSecurity mailinglist.

Given this is a problem outside CRS and nothing we can solve, I am closing this issue.
