### ISSUE TITLE
Help create rule for Wordpress and ACF (Advanced Custom Fields)

### ISSUE THREAD

**Issue by mocodev** [coreruleset/coreruleset#2066]
#2065 

Wondering if someone could help create a rule/expression to allow WordPress posts that contain ACF fields to properly preview and save.

**Comment by azurit** [comment]
Can you post a full log from request blocking?

**Comment by petskratt** [comment]
I've had success with updating rules (one of them to be included after CRS):

`# exclude XSS-related rules that are triggered by HTML fragments 
SecRuleUpdateTargetById "941100,941160" "!ARGS:/^acf\[field_.*$/"
# ... or exclude CRS completely
SecRuleUpdateTargetByTag "OWASP_CRS" "!ARGS:/^acf\[field_.*$/
`

**Comment by dune73** [comment]
Thank you @petskratt. I think this is all we need here. I'm removing the *need more info* label.

Do you think you could a PR for this to blend in with the existing WordPress rule exclusions?

If it's too much of a hassle, we'll look for somebody from the dev team.

**Comment by RedXanadu** [comment]
@dune73 I was thinking about this issue. How would the example rule exclusions be added to the existing Wordpress RE file?

Can the example `SecRuleUpdateTargetById` rule shown above be expressed as a runtime exclusion using a `ctl:ruleRemoveTargetById` action? It seems to rely on a regular expression to handle dynamic argument names.

**Comment by dune73** [comment]
Hmm. It seems I did not really look at this. The runtime rule exclusions (-> ctl) won't work with regexes. It's a major shortcoming with ModSecurity unfortunately.

Guess, we're at a loss here once more. And if the parameter name really is free-form, then things are really difficult.

**Comment by dune73** [comment]
I do not think we can do a reasonable generic rule exclusion here. The `SecRuleUpdateTargetById` examples above will work and people will maybe find their way to this issue and suggestion, but I guess we will have to close this issue without a real solution.

**Comment by RedXanadu** [comment]
@dune73 Is there a reason that a rule exclusion file like `REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf` cannot have a corresponding post-CRS rule exclusion file, e.g. `RESPONSE-999.9001-WORDPRESS-EXCLUSION-RULES-AFTER-CRS.conf`?

**Comment by azurit** [comment]
Current version of WordPress exclusion package is written for vanilla WordPress, it does not support any plugin of theme.

**Comment by dune73** [comment]
We've never done an AFTER RE file. Namely because we want to enable / disable RE files based on crs-setup.conf and the `SecRuleUpdateTargetById` directive that people would want to place in such a file can't be skipped.

However, when we think about rule exclusion plugins, where you enable a plugin by placing it / linking it in the right folder, then this could become an option. Actually it's an argument for exclusion plugins since this would allow us to use regular expression to define parameter names - and it would be an argument for this way of enabling plugins (vs. enabling them via a variable setting, like @lifeforms would prefer).

**Comment by lifeforms** [comment]
So, with our current architecture we can't exlude those fields because ACF sends random parameter names and the ModSecurity engine can't add these before the rules are declared - only after. This is not possible with our current file structure. We are considering a complete revamp of the CRS where regexp'ed exclusions WILL be possible, and we will take this issue into consideration for the next release.

**Comment by dune73** [comment]
Following up on this: We will take this issue or the more general problem behind it to our Developer Summit in October where this will be discussed. It's likely to remain open until then.

**Comment by dune73** [comment]
OK. So we looked at this problem in the dev retreat in October. 

We took the decision to move all Rule Exclusion packages to plugins. 

This will ultimately allow REs like the one needed / proposed here, since we can then do _after-REs_.

**Comment by dune73** [comment]
Sorry for not getting to work on this. The team is currently swamped (see https://coreruleset.org/20220711/update-on-crs-4-0-release-delay/).

We're happy to accept pull requests for this though.

**Comment by fzipi** [comment]
@azurit Do we want to move this issue to the wordpress plugin?

**Comment by azurit** [comment]
Probably no, i suggest to close it.
