### ISSUE TITLE
Rule id: 930100 does not check for Single dot directory and semicolon

### ISSUE THREAD

**Issue by vibhasethi** [coreruleset/coreruleset#2105]
Rule id 930100 for Directory Traversal Attacks does not check for single dot directory and semicolon

Related CVE: 
1. Path equivalence (/./) Single dot directory - https://cwe.mitre.org/data/definitions/55.html

Directory Traversal using Semicolon:
Apache Tomcat Semicolon Directory Traversal Vulnerability - https://www.rapid7.com/db/vulnerabilities/http-apache-tomcat-semicolon-dir-traversal/

**Comment by airween** [comment]
Hi @vibhasethi,

thanks for the spotting! We will investigate this issue soon.

**Comment by dune73** [comment]
Just for the record. 

```
$ curl -v --path-as-is "http://localhost/./index.html"
$ curl -v --path-as-is "http://localhost/;index.html"
```

**Comment by dune73** [comment]
We talked about this issue at our [recent project meeting](https://github.com/coreruleset/coreruleset/issues/2074#issuecomment-856173925).

We think the semicolon is a very old CVE that does not really concern us that much and we don't really see who the dot can pose a problem, also since it's being normalized away in CRS via the path normalization transformations.

So we are closing this issue.

If you think it really is a security concern, then please reopen and elaborate.
