### ISSUE TITLE
Rule 941140 FP

### ISSUE THREAD

**Issue by recurlybil** [coreruleset/coreruleset#2162]
Rule 941140 incorrectly matches on the following test strings:

<meta charset="utf-8" />

<style type="text/css">

**Comment by dune73** [comment]
Hey @recurlybil, thanks for writing in and sorry for the late response.

Why do you think this is incorrect? I admit it is not an attach. But it's obviously code and we try not to allow code with the 941xxx rules. You could say 941140 is misdetecting here, while 941150 is correct, but honestly, the rules are never that sharp and there is plenty of overlapping. Also because the code is overlapping a lot and the differences in the code are subtle.

**Comment by recurlybil** [comment]
I thought the rule was detecting only JavaScript?  Is it also detecting HTML and CSS?  If so, why not just look for angled brackets?

**Comment by lifeforms** [comment]
We have discussed the problem.

In general, HTML input needs to be excluded with a custom rule. There is simply too much evilness in it and there’s no way CRS is going to accept it.

We could weaken our defenses a bit, by changing this particular rule, but likely, user input would still hit a lot of other rules. There is no reasonable short-term path that would reach the goal of making CRS work well with HTML.

I think your only option is to create an exception for this input field in your webserver config. 

It requires some work, but there are excellent tutorials available at:

- https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/
- https://www.netnea.com/cms/nginx-tutorial-8_handling-false-positives-modsecurity-core-rule-set/

I'm closing this issue because we cannot provide a fix for it - but If you need any help feel free to ask us.
