### ISSUE TITLE
A single file that inculde all the owasp rules for modsecurity

### ISSUE THREAD

**Issue by leyao-daily** [coreruleset/coreruleset#2203]
I am wondering if there is a file or strings that include all the rules.
I want to load all the rules once using `modsec_rules_->load(rules_strings)` and define the rules_string as hardcode.

**Comment by airween** [comment]
Hi @leyao-daily,

sorry to say, but your issue is a bit incomplete (and I'm not sure this is a CRS issue).

Is your mentioned method comes from libmodsecurity3's [load](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/rules_set.cc#L66-L83) method?

If yes, you can make a trick:

```bash

cat << EOF > /path/to/coreruleset/owasp-crs.load
include /path/to/coreruleset/crs-setup.conf
Include /path/to/coreruleset/rules/*.conf
EOF

cat << EOF > /pat/to/your/hardcoded.conf
include /path/to/your/modsecurity.conf
include /path/to/coreruleset/owasp-crs.load
EOF
```
Then you should use the file `/pat/to/your/hardcoded.conf` as hardcoded `rules_strings`.

Btw I think you can call the `->load()` method as many time as you want, so you can use:

```C++
modsec_rules_->load("/path/to/your/modsecurity.conf");
modsec_rules_->load("/path/to/coreruleset/owasp-crs.load");
```

If the context is something different, please clarify it, we try to help you.

**Comment by leyao-daily** [comment]
Thanks for your reply.
And what I want is to avoid reading a file system. I want define the eg.
`rules_strings = SecRuleEngine On
                    SecAuditEngine On
                    SecAuditLogType Serial
                    SecAuditLog /etc/modsecurity_audit.log
                    SecRequestBodyAccess On
                    SecResponseBodyAccess On
                    SecRule ARGS:param1 "test" "id:1,phase:1,log,status:400,msg:'Test rule'"
                    SecRule ARGS:param2 "test" "id:2,phase:1,deny,status:400,msg:'Test rule'"
                    SecRule REQUEST_BODY  "blocktest" "id:3,phase:2,deny,status:400,msg:'Test rule'"
                    SecRule RESPONSE_HEADERS:Content-Type "application/json; charset=utf-8" "id:4,phase:3,log,status:400,msg:'Test rule'"
                    SecRule RESPONSE_BODY "@contains test" "id:5,phase:4,log,status:400,msg:'Test rule'"

And load it to modsecurity module. I want get the all the owasp rules like the above into one stringvalue.

**Comment by airween** [comment]
Sorry, looks like `->load()` does this. The file handler method is `loadFromUri()`.

So you just want to concatenate the all rules and paste the result to your source?

Then you should try:

```bash
cat /path/to/your/modsecurity.conf > /tmp/modsec.conf
cat /path/to/your/coreruleset/crs-setup.conf >> /tmp/modsec.conf
for f in /path/to/your/coreruleset/rules/*.conf; do cat ${f} >> /tmp/modsec.conf; done
```
and you will get the file `/tmp/modsec.conf`.

Btw I'm not sure that will work, because there are several external resources what CRS rules use, see the data files in [this](https://github.com/coreruleset/coreruleset/tree/v3.4/dev/rules) directory.

**Comment by dune73** [comment]
Does this address your needs @leyao-daily? If yes, please close the issue.

**Comment by leyao-daily** [comment]
I would like to have a try. Thanks!!

**Comment by dune73** [comment]
You're most welcome.
