### ISSUE TITLE
XSS: WAF on Azure Application gateway

### ISSUE THREAD

**Issue by yasuyuki-satake** [coreruleset/coreruleset#2219]
### Describe the bug

We are using WAF rule (OWASP CRS 3.0) on Azure Application gateway.
But we face something wierd situation.
We got an answer from Microsoft support, they said I need to confirm this with you.
It seems below is affected a rule id = 941100 (XSS Attack Detected via libinjection) on it.

Do you have any comment or suggestion on this?

### Steps to reproduce
HTML
<img width="332" alt="スクリーンショット 2021-10-05 18 14 54" src="https://user-images.githubusercontent.com/12962785/135995452-5d6c17ae-1936-42f9-bb50-77a16dc72184.png">

ng: https://www.AAAAA.co.jp/lp/on_client3.html?a=a
 -> message: [GET https://www.AAAAA.co.jp/lp/test.css net::ERR_ABORTED 403 (ModSecurity Action)]
<img width="375" alt="スクリーンショット 2021-10-05 18 13 18" src="https://user-images.githubusercontent.com/12962785/135995579-0b409ee4-5d0e-4a6c-b7b7-965f0766c056.png">
this css is not read as 403.

ok: https://www.AAAAA.co.jp/lp/on_client3.html
ok: https://www.AAAAA.co.jp/lp/off_client3.html
ok: https://www.AAAAA.co.jp/lp/off_client3.html?a=a
* need to clear browser cache every time
* on_client3.html and off_client3.html are same HTML as above.
<img width="296" alt="スクリーンショット 2021-10-05 18 13 25" src="https://user-images.githubusercontent.com/12962785/135995504-1418e6fd-87ea-4a5a-a27c-5772fc58d5ca.png">

NG cases are:
1. file name is always started with "on".
2. url parameter is attached

### Your Environment
WAF rule (OWASP CRS 3.0) on Azure Application gateway

**Comment by yasuyuki-satake** [comment]
Hi @RedXanadu 

Thank you for your comment.

The below is an audit log on our Azure.
* domain is masked..

{ "resourceId": "/SUBSCRIPTIONS/0F1E0263-6464-44DD-9858-F81C8F3183DD/RESOURCEGROUPS/ADECCO-PROD-WESTJP/PROVIDERS/MICROSOFT.NETWORK/APPLICATIONGATEWAYS/AAAAA-PROD-WESTJP-AGW", "operationName": "ApplicationGatewayFirewall", "time": "2021-09-30T04:43:16.7067560Z", "category": "ApplicationGatewayFirewallLog", "properties": {
  "instanceId": "ApplicationGatewayRole_IN_2",
  "clientIp": "150.249.250.22",
  "clientPort": "0",
  "requestUri": "/lp/test.css",
  "ruleSetType": "OWASP",
  "ruleSetVersion": "3.0",
  "ruleId": "941100",
  "ruleGroup": "941-APPLICATION-ATTACK-XSS",
  "message": "XSS Attack Detected via libinjection",
  "action": "Matched",
 "site": "Global",
  "details": {
    "message": "Warning. detected XSS using libinjection.",
    "data": "Matched Data: https://www.AAAAA.co.jp/lp/on_client3.html?a=a",
    "file": "rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf",
    "line": "54"
  },
  "hostname": "www.AAAAA.co.jp",
  "transactionId": "17221769383848764120"
}}

Thanks in advance

**Comment by RedXanadu** [comment]
Thank you for that information.

Is there any additional information available about _which variable_ matched? For example, I was hoping to see a log line like the following:

`"data": "Matched Data: https://www.AAAAA.co.jp/lp/on_client3.html?a=a found within REQUEST_HEADERS:Referer: https://www.AAAAA.co.jp/lp/on_client3.html?a=a"`

Because the matched data is a full URL, I'm 90% sure that the `Referer` HTTP header was the cause of your false positive. It would be nice to be certain of that, though.

---

Let us assume that the `Referer` header is the issue. You have two options to resolve this issue.

### Option 1

Are you running your WAF at paranoia level 1? If so, you could resolve this issue by using a newer version of the Core Rule Set. This issue is resolved in CRS version 3.0.1 and later. (The `detectXSS` operator can cause many false positives when it checks the `Referer` header. This action is likely the cause of your issue. This action was moved to paranoia level 2 in CRS version 3.0.1.)

### Option 2

If you cannot use a more recent CRS version then you could instead use a rule exclusion. You could exclude the `Referer` header from being processed by the offending rule, rule 941100. You could use a rule exclusion like the following:

```
SecRuleUpdateTargetById 941100 "!REQUEST_HEADERS:Referer"
```

This is how the rule exclusion would ordinarily be applied in a configuration file, for example with Apache. There may be an Azure-specific way to achieve this through the Azure web UI, however.

**Comment by yasuyuki-satake** [comment]
Hi @RedXanadu 

Thank you for your comment and suggestion.
We are using WAF rule (OWASP CRS 3.0) on Azure Application gateway.
it means I think we are running WAF at paranoia level 1.
But I can not see newer CRS version on Azure Application gateway which we are using..
I will check if we will use newer CRS version on Azure Application gateway.
Anyway, thank you for your kind help!

**Comment by yasuyuki-satake** [comment]
@RedXanadu 
Thanks for your kindness.
As far as I checked, If we want to use CRS 3.1 on Azure Application gateway, we need to re-create Application gateway and attached it.
I will talk with my team if we could upgrade Application gateway, or take easy solution (disable rule 941100).
close with comment for now... thank you.
