### ISSUE TITLE
Website GDPR compliance

### ISSUE THREAD

**Issue by lifeforms** [coreruleset/coreruleset#2304]
### Motivation

Our website now contains a Matomo tracker hosted by Netnea that logs some visitor data. To be GDPR compliant, we must inform our visitors about any data that we collect.

### Proposed solution

- [x] Matomo at Netnea should be configured to anonymize IP addresses.
- [x] Create a Privacy Statement that explains to the visitors the way we use their data.
- [x] If the demo/sandbox also logs data, the Privacy Statement should also mention this. (can be added later)
- [x] We also should mention that we keep access_logs for some time but they are erased periodically.

### Alternatives

- Add a cookie banner so that the visitor is able to opt-out of any data collection. In my analysis, as long as we are anonymizing the Matomo tracker, there is no legal requirement for a user to opt-out of the collection, and we do not need an intrusive cookie banner.

**Comment by lifeforms** [comment]
I can add a privacy statement to the website, @dune73 can you confirm that Matomo is configured in anonymizing mode?

**Comment by lifeforms** [comment]
Is data (planned to be) logged by the demo site? Which data, I assume the whole request, including source IP address (personal data)?

**Comment by dune73** [comment]
I'm all for anonymizing. Will keep you posted when I have a bit of time at hand.

Until then: netnea is hosted in Switzerland and Switzerland is not GDPR country. And we're an OWASP project and OWASP is an American org, again not GDPR country. Does any of this influence our need for compliance?

And given we are a project and not really a legal entity, I am not really afraid of somebody suing us. So I would try and avoid the cookie banner.

**Comment by lifeforms** [comment]
We have to comply with the GDPR even if we are storing data of just one Europese citizen - I think they even did not define this as a citizen, but someone "within the EU" - So even if you made the mistake of crossing a border, we will protect your data! 😊

**Comment by dune73** [comment]
I agree with you, also on the GDPR part.

I have now enabled IP address anonymization. And we can set up privacy statement.

Here is my proposal:

---

# OWASP ModSecurity Core Rule Set Project Privacy Policy

Our project is part of the Open Web Application Security Project (OWASP). This privacy policy will explain how our organization uses the personal data we collect from you when you use our website.

Topics:

* What data do we collect?
* How do we collect your data?
* How will we use your data?
* How do we store your data?
* How do we use cookies?
* Changes to our privacy policy
* How to contact us
* How to contact the appropriate authorities

### What data do we collect?

Our Company collects the following data:

* Anonymized IP addresses

### How do we collect your data?

You directly provide our project with most of the data we collect. We collect data and process data when you:

* Browse our website with your browser

### How will we use your data?

Our project collects your data so that we can:

* Review website usage
* Review usage / session patterns on website
* Review interest of our users for certain aspects of our project (namely when reviewing the usage patterns of our documentation, e.g. which rule descriptions are loaded the most often)

We can rule any sharing of your data with anybody outside our project.

### How do we store your data?

Our company securely stores your ip address in the log files for days or weeks and your anonymized ip address for long term storage in a database.

### What are your data protection rights?

Our Company would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:

The right to access – You have the right to request Our Company for copies of your personal data. We may charge you a fee for this service.

The right to erasure – You have the right to request that Our Company erase your personal data, under certain conditions.

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us at our email:

Or write to us via the email addresses published on this website.

### How do we use cookies?

Our project uses cookies to understand how our users use our website.

### Changes to our privacy policy

Our project keeps its privacy policy under regular review and places any updates on this web page. This privacy policy was last updated on 14 November 2022.

### How to contact us

If you have any questions about our project's privacy policy, the data we hold on you, or you would like to exercise one of your data protection rights, then please understand that we're a volunteer driven project trying to write rules to protect our users from malicious attacks. That is our priority. But feel free to contact us and we'll make sure we have a response for you in due time.

Please email us the addresses published here on the website.

### How to contact the appropriate authority

Should you wish to report a complaint or if you feel that Our Company has not addressed your concern in a satisfactory manner, you may contact the authorities.

* Our website is hosted in the Netherlands.
* The database holding your anonymized ip addresses is hosted in Switzerland.
* We're part of the OWASP family and OWASP is an American company.

Please pick one country's privacy authorities as you see fit.

**Comment by dune73** [comment]
What's the deal with "Personal data of blog editors"?

**Comment by lifeforms** [comment]
Wow, thank you for the text. That is a great start.

> What's the deal with "Personal data of blog editors"?

This was a note to myself. If we give someone an account to edit our website, we will store that person's name and e-mail address in WordPress.

**Comment by dune73** [comment]
Given we only give that to people close to our project, I do not think we need to cover this in a public privacy statement.

**Comment by lifeforms** [comment]
Dune's text is now incorporated in the website with small fixes at https://coreruleset.org/privacy-policy/
A link to the privacy policy is added to WordPress' footer.
This should bring us in compliance, thank you for the very nice text @dune73 .

**Comment by dune73** [comment]
Thank you! You're most welcome. Glad you like it. It was a quick thing.
