### ISSUE TITLE
Refactor the CRS scoring variables

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#2319]
The variables used to aggregate the anomaly scores are used very inconsistently (see also: https://github.com/coreruleset/coreruleset/issues/1896).

This becomes very apparent by comparing the rules `949110` and `959100` with respects to how `anomaly_score` and `inbound_anomaly_score` are used compared to `anomaly_score` and `outbound_anomaly_score`. The way the variables are named appear to be the complete inverse of how they are used. This is why the following lines of these rules are so different:
```
# 949110
SecRule TX:ANOMALY_SCORE "@ge %{tx.inbound_anomaly_score_threshold}" \
[...]
    setvar:'tx.inbound_anomaly_score=%{tx.anomaly_score}'"

# 959100
SecRule TX:OUTBOUND_ANOMALY_SCORE "@ge %{tx.outbound_anomaly_score_threshold}" \
[...]
    setvar:'tx.anomaly_score=+%{tx.outbound_anomaly_score}'"
```

For incoming scores, `anomaly_score` is used to aggregate the scores from the different paranoia levels and is then _assigned_ to `inbound_anomaly_score`. For outgoing scores, `outbound_anomaly_score` is used to aggregate the scores from the different paranoia levels and is then _added_ to `anomaly_score`.

---

Aside from the confusion there is no functional problem with this in itself. However, the confusion can lead to problems later on as the semantics of variables is not clear. This is the case with rule `980120` for example.

The variable `INBOUND_ANOMALY_SCORE` remains unset if `anomaly_score` is less than `inbound_anomaly_score_threshold` in phase 2. The result of this is that the log entry for this rule contains contradictory information if it is even printed:
* `Total Inbound Score: 0`
* `individual paranoia level scores: 10, 0, 0, 0`
```
[Thu Nov 25 14:30:48.269676 2021] [:error] [pid 344927:tid 140178457110272] [client 127.0.0.1:57402] [client 127.0.0.1] ModSecurity: Warning. Operator GT matched 1 at TX:executing_anomaly_score. [file "rules/RESPONSE-980-CORRELATION.conf"] [line "77"] [id "980120"] [msg "Inbound Anomaly Score (Total Inbound Score: 0 - SQLI=0,XSS=0,RFI=0,LFI=0,RCE=10,PHPI=0,HTTP=0,SESS=0): individual paranoia level scores: 10, 0, 0, 0"] [ver "OWASP_CRS/3.4.0-dev"] [tag "event-correlation"] [hostname "localhost"] [uri "/index.html"] [unique_id "YZ@QCFM9g-bdcxDv4w5IMgAAAAA"]
```

The correlation rules in general are very difficult to understand because of this.

---

The inconsistencies go even further than this.

For example, for incoming scoring, the scores are increased as follows:
```
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}'"
```
For outgoing scoring on the other hand, there are always two variables that are increased:
```
    setvar:'tx.outbound_anomaly_score_pl1=+%{tx.error_anomaly_score}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.error_anomaly_score}'
```

This not only redundant but allows for further inconsistencies later on. For example, if we compare the blocking rules for incoming and outgoing, as well as for early and regular blocking, we get three different ways to count the scores:
```
# incoming, early
SecRule TX:PARANOIA_LEVEL "@ge 1" \
    "id:949052,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.anomaly_score=+%{tx.anomaly_score_pl1}'"
```
```
SecRule TX:PARANOIA_LEVEL "@ge 1" \
    "id:949060,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.anomaly_score=+%{tx.anomaly_score_pl1}'"
```
```
# outgoing, early
SecRule TX:PARANOIA_LEVEL "@ge 1" \
    "id:959052,\
    phase:3,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.outbound_anomaly_score=+%{tx.anomaly_score_pl1}'"
```
```
# outgoing, regular
SecRule TX:PARANOIA_LEVEL "@ge 1" \
    "id:959060,\
    phase:4,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.outbound_anomaly_score=+%{tx.outbound_anomaly_score_pl1}'"
```

---

To address the above mentioned issues, the semantics and naming of the anomaly scoring variables have to be refactored across the entire rule set. To have consistent semantics and descriptive naming of variables, I would propose the following:

* Phase 1 & 2
    * `executing_inbound_anomaly_score_pl[1234]`: Sum up the scores of triggered rules during request processing (indirectly limited by `executing_paranoia_level`)
    * `inbound_anomaly_score_pl[1234]`: removed because not used
    * `inbound_anomaly_score`: Sum up the values of `executing_inbound_anomaly_score_pl[1234]` during blocking evaluation according to `paranoia_level` (blocking decision is based on this)
* Phase 3 & 4
    * `executing_outbound_anomaly_score_pl[1234]`: Sum up the scores of triggered rules during response processing (indirectly limited by `executing_paranoia_level`)
    * `outbound_anomaly_score_pl[1234]`: removed because not used
    * `outbound_anomaly_score`: Sum up the values of `executing_outbound_anomaly_score_pl[1234]` during blocking evaluation according to `paranoia_level` (blocking decision is based on this)
* Phase 5
    * `executing_inbound_anomaly_score`: Sum up the values of `executing_inbound_anomaly_score_pl[1234]`
    * `executing_outbound_anomaly_score`: Sum up the values of `executing_outbound_anomaly_score_pl[1234]`
    * `executing_anomaly_score_pl[1234]`: Sum up the values of `executing_inbound_anomaly_score_pl[1234]` and `executing_outbound_anomaly_score_pl[1234]` per paranoia level
    * `executing_anomaly_score`: removed because not used
    * `anomaly_score_pl[1234]`: removed because not used
    * `anomaly_score`: removed because not used

Users that log scoring variables might have to change their log formats as follows (alternatively, additional variables could be created to act as aliases to allow for a grace period):
* `anomaly_score` ->  `inbound_anomaly_score`
* `anomaly_score_pl[1234]` -> `executing_inbound_anomaly_score_pl[1234]`
* `outbound_anomaly_score_pl[1234]` -> `executing_outbound_anomaly_score_pl[1234]`

**Comment by fzipi** [comment]
Hey @studersi ! Nice to see you here. Nice explanation and writing. We are going to chat about this in our next monthly meeting, were you are welcome of course!

**Comment by 53cur3M3** [comment]
This looks well thought out, and having consistent naming and usage seems sensible. The only two things I wonder about with the list of proposed changes is:
1) Proposals to remove currently unused variables - are we sure these are not wanted in the future? Or potentially desirable to be utilised by plugins?
2) It would be nice if the executing anomaly score variables followed the same structure / pattern, and in this proposal they seem to differ (ie. propose to get rid of inbound_anomaly_score_pl[1234] and outbound_anomaly_score_pl[1234] but keeping executing_inbound_anomaly_score_pl[1234] and executing_outbound_anomaly_score_pl[1234]

**Comment by studersi** [comment]
Hi @fzipi, thanks, @dune73 has also suggested we discuss it at the meeting. Looking forward to see you there!

@53cur3M3 
1. Yes that might be worth considering.
2. Not sure I understand correctly. Would you rename these variables to something different? The scores per paranoia level are named `executing_*` because whether they are used or not depends on `executing_paranoia_level`, not `paranoia_level`.

**Comment by RedXanadu** [comment]
Using `executing_inbound_anomaly_score_plX` seems confusing. Is there a reason to throw in the "executing" concept into the mix? Is there a reason why we couldn't standardise on `inbound_anomaly_score_pl[1234]` and `outbound_anomaly_score_pl[1234]`?

---

It looks like `ANOMALY_SCORE` has been kept around for legacy reasons. Is it still needed?

```
# Note: This rule also sets the 'tx.anomaly_score' variable.
# That variable name was formerly used in CRS, but not any longer.
# However, Jwall AuditConsole depends on this exact variable name.
# Without setting it, the 'Outbound Score' in the AuditConsole GUI would always be 0.
```

Are there lots of people using 'Jwall AuditConsole'?

---

I couldn't understand why rule 980120 seems to work for me (on 3.4/dev), even if a transaction doesn't reach the inbound anomaly score threshold.

I did a bit of digging, and it looks like 980120 works by chance:

```
[06/Dec/2021:16:39:49.432296 +0000] [...][4] Executing operator "lt" with param "%{tx.inbound_anomaly_score_threshold}" against TX:inbound_anomaly_score.
[06/Dec/2021:16:39:49.432299 +0000] [...][9] Target value: "0"
[06/Dec/2021:16:39:49.432307 +0000] [...][9] Resolved macro %{tx.inbound_anomaly_score_threshold} to: 20
[06/Dec/2021:16:39:49.432311 +0000] [...][4] Operator completed in 9 usec.
[06/Dec/2021:16:39:49.432316 +0000] [...][4] Rule returned 1.
```

`Target value: "0"`. I guess Apache treats the empty `ANOMALY_SCORE` variable as a "0", so rule 980120 has the intended effect.

That happy little coincidence may not work on other engines, though (I haven't tested nginx or Coraza to see if they do the same thing).

**Comment by studersi** [comment]
@RedXanadu 

---

Yes, there is a reason for taking `executing` into the mix. The variables that count the score per paranoia level are populated according to `executing_paranoia_level` not according to `paranoia_level`. Only when they are summed up to evaluate blocking, is `paranoia_level` taken into account.

---

Not sure how many people use Jwall but I would not mind keeping the variable `ANOMALY_SCORE` around.

---

Yes, `980120` basically works again on Apache, except that there are inconsistencies with the output in certain cases. For the example above I specifically constructed an example that would show this incorrect behaviour.

See also: https://github.com/coreruleset/coreruleset/issues/1896#issuecomment-704985979
> And maybe a small correction: With the fix in #1898 the Rule 980120 is not broken anymore by this here issue. It works as intended, though the actual reason it works is not intuitive and not what you would expect.

**Comment by studersi** [comment]
Naming alternatives for the types of variables based on discussion in https://github.com/coreruleset/coreruleset/issues/2291 plus some additional options:

* Paranoia Level
  * Active
  * Blocking
  * Triggering
  * Intervening
  * Restricting
  * Enforcing
  * Filtering
  * Sieving
  * Sifting
* Executing Paranoia Level
  * Passive
  * Non-blocking
  * Detection
  * Logging
  * Monitoring
  * Non-intervening
  * Observing
  * Auditing
  * Probing
  * Surveilling
  * Surveying
  * Examining
  * Perusing
  * Screening

**Comment by dune73** [comment]
The choice is pure torture...

**Comment by studersi** [comment]
How do we proceed here?

**Comment by franbuehler** [comment]
Outcome [issue meeting December 2021](https://github.com/coreruleset/coreruleset/issues/2291#issuecomment-987122691): We get the feeling nobody has a clear opinion on this. And it's a big step. So let's think about this some more and return to it in January.

**Comment by fzipi** [comment]
Not perfect, but my choices are:

- blocking / logging
- enforcing / auditing
- enforcing / logging
- blocking / auditing

**Comment by RedXanadu** [comment]
These work well, IMO:
- Blocking/Detection
- Enforcing/Detection

Or maybe, to keep things in sync with the engine:
- Blocking/DetectionOnly
- Enforcing/DetectionOnly

**Comment by theseion** [comment]
@RedXanadu Detection -> Detecting? Both should be verbs I think (in case of "DetectionOnly" that doesn't work of course).

**Comment by RedXanadu** [comment]
Maybe? I think "Detecting" sounds odd, but I don't have a rational reason for that! :)

**Comment by dune73** [comment]
Time to come to a conclusion here. @Studersi's analysis was profound and the proposal useful, but many of us were still not quite happy. (a) because of the general unhappyness with my term "executing", (b) because it felt we had not understood the problem deep enough and (c) because the reporting in the 980xxx rules was not covered enough. I fall in category (c).

We talked about this a lot in the meantime and nobody felt fit to refine the existing proposal or to take a decision.

But then I got the chance to trade in the migration of the DoS rule to a plugin against me working on this issue. Thanks @RedXanadu.

So here we go.

## The variables

The discussion favored to remove the `executing` and there was a preference for `detection` instead.  I think it is a good move to lean on the engine and to settle on `blocking` and `detectionOnly`.

Given this is going to be a major release, we can clear out all ambiguities and I propose to add the `blocking` prefix to the paranoia level variable.  This gives us

* `blocking_paranoia_level` : The basic PL variable. This is the PL we execute and block.
* `detectiononly_paranoia_level` : This is greater or equal than `blocking_paranoia_level` and defines the level whose rules are executed, potentiall executed without being used for the blocking decision.

And now for the simplification: Let's remove all prefixes from the scoring variables. We simply do this as follows:

* incoming_anomaly_score_pl1 : Sum of the anomaly score by the rules triggered during execution at PL 1
* incoming_anomaly_score_pl2 : Sum of the anomaly score by the rules triggered during execution at PL 2
* incoming_anomaly_score_pl3 : Sum of the anomaly score by the rules triggered during execution at PL 3
* incoming_anomaly_score_pl4 : Sum of the anomaly score by the rules triggered during execution at PL 4

And then - take note here! - we sum of these scores up to the `blocking_paranoia_level` and write them into:

* incoming_anomaly_score : Anomaly score used for the blocking decision.

Let's say, we have the following scores per paranoia level: `5-10-15-20` (thus all the rules executed on all PLs):

* If `blocking_paranoia_level` was 4, then the `incoming_anomaly_score` would be 50.
* If `blocking_paranoia_level` was 3, then the `incoming_anomaly_score` would be 30.
* If `blocking_paranoia_level` was 2, then the `incoming_anomaly_score` would be 15.
* If `blocking_paranoia_level` was 1, then the `incoming_anomaly_score` would be 5.

So if you report the scores on a single line (extended access log format as in my netnea tutorials) you get the following at `blocking_paranoia_level=2`:

5-10-15-20 15

These numbers will allow you to determine that 

* `blocking_paranoia_level` was 2
* `detectionOnly_paranoia_level` was 4

Given blocking and detectionOnly are the same level per default and raising the latter separately is advanced CRS business, I am sure we can guide people to understand the numbers even if `5-10-15-20 15` looks a bit odd at first sight.

The early blocking does not really affect any of this. The scores will simply be lower since only phase 1 is being covered.

And then we do the same for outgoing. Perfectly symmetrical.

As noted in the discussion, the JWall Audit Console makes use of `anomaly_score`. This console has been out of development for years - Christian Bockermann is a Professor now - but quite a few people and even integrators still use it.

I would hate to carry an unnecessary variable into a new major release because of some legacy software. But I think we can easily propose a rule in the documentation to set this. Or - very professional - provide a `jwall-compatibility-plugin` that sets the variable in question.


## The reporting in the 980xxx rules.

The whole 980xxx business is a mess. And I have been wanting to clean this up for a long time. If we are cleaning up the scoring, then let's address this too.

Here is what we need to provide:

* Some people want to see anomaly scores in the error log even if a request was not blocked
* We do separate category scores. We could think about including them in the blocking rules (949110 and friends), but maybe it's better to leave that aside.
* On NGINX it is not possible to report anomaly scores in the access log. So if you want a full overview, you need to write it into the error log. This can also include requests with score 0. Since you may want an easy way to determine how many requests passed the rule set without hitting any rules.

In order to satisfy all these needs, I suggest a variable `anomaly_score_reporting` with 4 possible values:

0 - No reporting beyond 949110 and friends
1 - Report the anomaly scores per PL and per category in 980xxx for those requests that have been blocked
2 - Report the anomaly scores per PL and per category in 980xxx for those requests that scored
3 - Report the anomaly scores per PL and per category in 980xxx for every requests, also requests with scores 0/0 (inbound/outbound)

Implementing this will be a bit of number juggling, but if you set the value to 0, then you can skip it all and I guess performance won't be such an issue that way.

**Comment by fzipi** [comment]
Here are my thoughts on this.

## The Variables

On the naming, I understand we rely on modsecurity for using `detectiononly`, but with more engines around the term might not stick anymore. I think it is clear enough when you say `blocking` and `detecting`, but maybe I'm being naive. We don't say `detection_and_blocking` and `detectiononly` for example. We assume that if the semantics on `blocking` imply that you detected first 🤷 . And if we are `detecting`, we are not `blocking`. Otherwise we would use `blocking` 😉 . In the end, as long as this is clearly documented, it doesn't matter too much. We can even use `logging` and `blocking`. And we can go for ever with this also. 🤣 

With respect to the additional variables and scoring, I understand what you are trying to do here, but at first sight looks like we are relying on assumed semantics that might be confusing. I guess we only need to be really clear when documenting, that's all.

The whole `PL1_score - PL2_score - PL3_score - PL4_score` looks good, but then if `PL3_score` is 0 (and probably `PL4_score` will be 0), we assume that `detection` is set to PL2, right? 

👉 What if the scores are *really* 0 there?

In the end... this is _configured_ by the security team, so _they_ know what has been configured... but can we "assume" `detection` was in PL2 for sure?

Regarding the JWall audit console, I'm not too worried. When this goes out, in a major release, I'm not seeing everyone jumping to change theirs for some time while they plan, etc, so we have some time to even send a patch if necessary.

## The reporting in the 980xxx rules

Very clever on this one 🥇 . I like the idea that reporting can be configured with that level of verbosity!

We should take care that logging can be easily parsed by integrators so it is easy to do faceted search in those values, and that's it.

**Comment by dune73** [comment]
Thank you very much for this useful and constructive feedback. I agree with all of it and I am particularly fond of the idea to write `blocking_(incom|outgo)ing_anomaly_score` and `detection_(incom|outgo)ing_anomaly_score`. This had not occurred to me.

I am leaving the previous proposal intact and bring a new version here:

---

## The variables

* `blocking_paranoia_level` : The basic PL variable. This is the PL we execute and block.
* `detection_paranoia_level` : This is greater or equal than `blocking_paranoia_level` and defines the level whose rules are executed, potentially executed without being used for the blocking decision.

And now for the simplification: Let's remove all prefixes from the scoring variables. We simply do this as follows:

* `incoming_anomaly_score_pl1` : Sum of the anomaly score by the rules triggered during execution at PL 1
* `incoming_anomaly_score_pl2` : Sum of the anomaly score by the rules triggered during execution at PL 2
* `incoming_anomaly_score_pl3` : Sum of the anomaly score by the rules triggered during execution at PL 3
* `incoming_anomaly_score_pl4` : Sum of the anomaly score by the rules triggered during execution at PL 4

And then - take note here! - we sum of these scores in two separate variables:

* `blocking_incoming_anomaly_score` up to the `blocking_paranoia_level`
* `detection_incoming_anomaly_score` up to the `detection_paranoia_level`

Let's say, we have the following scores per paranoia level: `5-10-15-20` (thus all the rules executed on all PLs, resulting in a `detection_incoming_anomaly_score` of 50):

* If `blocking_paranoia_level` was 4, then the `blocking_incoming_anomaly_score` would be 50.
* If `blocking_paranoia_level` was 3, then the `blocking_incoming_anomaly_score` would be 30.
* If `blocking_paranoia_level` was 2, then the `blocking_incoming_anomaly_score` would be 15.
* If `blocking_paranoia_level` was 1, then the `blocking_incoming_anomaly_score` would be 5.

The early blocking does not really affect any of this. The scores will simply be lower since only phase 1 is being covered.

And then we do the same for outgoing. Perfectly symmetrical.

As noted in the discussion, the JWall Audit Console makes use of `anomaly_score`. This console has been out of development for years - Christian Bockermann is a Professor now - but quite a few people and even integrators still use it.

I would hate to carry an unnecessary variable into a new major release because of some legacy software. But I think we can easily propose a rule in the documentation to set this. Or - very professional - provide a `jwall-compatibility-plugin` that sets the variable in question.



## The reporting in the 980xxx rules.

The whole 980xxx business is a mess. And I have been wanting to clean this up for a long time. If we are cleaning up the scoring, then let's address this too.

Here is what we need to provide:

* Some people want to see anomaly scores in the error log even if a request was not blocked
* We do separate category scores. We could think about including them in the blocking rules (949110 and friends), but maybe it's better to leave that aside.
* On NGINX it is not possible to report anomaly scores in the access log. So if you want a full overview, you need to write it into the error log. This can also include requests with score 0. Since you may want an easy way to determine how many requests passed the rule set without hitting any rules.

In order to satisfy all these needs, I suggest a variable `anomaly_score_reporting` with 4 possible values:

0 - No reporting beyond `949110` and friends
1 - Report the anomaly scores per PL, the blocking and detection, and per category in 980xxx for those requests that have been blocked
2 - Report the anomaly scores per PL, the blocking and detection, and per category in 980xxx for those requests that scored
3 - Report the anomaly scores per PL, the blocking and detection, and per category in 980xxx for every requests, also requests with scores 0/0 (inbound/outbound)

Implementing this will be a bit of number juggling, but if you set the value to 0, then you can skip it all and I guess performance won't be such an issue that way.

**Comment by theseion** [comment]
Now it is coming together! That was worth the wait :)

**Comment by dune73** [comment]
Yes, I think so too. And I'm astonished how simple this solution really is. Thanks to everybody for taking part.

**Comment by RedXanadu** [comment]
One more quibble about the language/terms…

In the **code**, should be be consistent with our use of "in*/out*" terms?

v3.4 seems to use mostly **inbound** and **outbound** in the code (variables, `msg` actions, comments, etc.), but we also mix in some _incoming_ and _outgoing_.

Should we stick with inbound/outbound or move to incoming/outgoing? It feels like it should be consistent, whichever way we go.

It's probably less important when talking about the concepts / in discussion pieces like blog posts, documentation, etc., but it feels like the _code_ should be consistent throughout and use one set of terms.

**Comment by dune73** [comment]
I second that, even if I was not aware of the unsystematic use so far.

Which one is more adequate from your native speaker perspective?

**Comment by RedXanadu** [comment]
I would say, stick with "inbound/outbound", as used in v3.3.2. So, `inbound_anomaly_score_pl1`, `blocking_inbound_anomaly_score`, etc. (I checked the opinion of a colleague, so you have a sample size of 2 :) )

Also, TIL that a few of the HTTP RFCs define and use inbound/outbound, so we'd be in good company:

> The terms "inbound" and "outbound" are used to describe directional requirements in relation to the request route: "inbound" means toward the origin server and "outbound" means toward the user agent.

**Comment by dune73** [comment]
Thank you.

@studersi : What do you think?

**Comment by studersi** [comment]
I think it is a good suggestion to consistently use inbound/outbound.

**Comment by dune73** [comment]
I just stumbled over a particular case where rules in phase 1 and redirect bring a bit of a messy situation.

Here is the log:

```
42.83.147.34 - - [2022-02-22 07:49:07.139947] "GET / HTTP/1.1" 301 235 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)Chrome/74.0.3729.169 Safari/537.36" "text/html; charset=utf-8" 49512 www.netnea.com 192.168.3.7 443 - - + "ReqID--" YhSHY48c5yRLRsVH7ShXXQAAAAo TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 924 5893 -% 11555 8347 8727 676 5-0-0-0 0-0-0-0 0 0
```

So we have a PL1 score of 5, but an overall inbound anomaly score of 5.

What happened is the following: 
* Phase 1 has a hit, PL1 anomaly score is being set
* Apache does a redirect
* Phase 2 is not being executed, thus overall anomaly score is not summed up
* Phase 5 happens and overall inbound anomaly score is still 0, that number is being written to env variable and later logged in access log.

**Comment by fzipi** [comment]
You mean each phase should be adding their scoring to the overall?

**Comment by dune73** [comment]
I do know how to solve this in an elegant way, I just think we need a solution if phase 2-4 are skipped.

**Comment by studersi** [comment]
I think we can close this since https://github.com/coreruleset/coreruleset/pull/2417 was merged and https://github.com/coreruleset/coreruleset/issues/2319#issuecomment-1047503932 is tracked in https://github.com/coreruleset/coreruleset/issues/2475.
