### ISSUE TITLE
False Positives with PL4 rule 920274 (msg: Invalid character in request headers (outside of very strict set))

### ISSUE THREAD

**Issue by franbuehler** [coreruleset/coreruleset#2361]
### Description

I have a lot of false positives with PL4 rule 920274 (I know it's PL4!)
The rule's message is: `Invalid character in request headers (outside of very strict set)`

- [Comment, what characters are allowed](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L528)
- [Link to rule](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1564)

### Audit Logs / Triggered Rule Numbers

Although it is a PL4 rule, in my opinion it is far too strict and I would like to relax it. 

Rule violations I often see:

- `Sec-CH-UA`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-UA. Hint: REQUEST_HEADERS:Sec-CH-UA-Mobile is already excluded from this rule.
- `REQUEST_HEADERS:from=googlebot(at)googlebot.com`
- `REQUEST_HEADERS:x-authenticated-user=someone@somewhere.xy`
- `REQUEST_HEADERS:via=1.1 172.x.y.z (McAfee Web Gateway 10.2.3.38089)` or other versions
- `REQUEST_HEADERS:x-user-identity=name@somedomain.xy` -  Exchange autodiscover requests
- `REQUEST_HEADERS:x-anchormailbox=name@somedomain.x`y - Exchange autodiscover requests
- `REQUEST_HEADERS:from=bingbot(at)microsoft.com` - bingbot indexing

I would like to do the following two changes to the rule:

1. Add an exclusion for `Sec-CH-UA` like we already have for `Sec-CH-UA-Mobile`
2. Add the brackets `(` and `)` and maybe the `@` to the list of allowed characters

What do you think. Is it worth improving a PL4 rule? 
I would say yes, because I think we should always allow compliant requests, even at PL4.

**Comment by lifeforms** [comment]
I think it's worth doing a special case for `Sec-CH-UA`.

I am scared of adding `(` and `)` to the list of allowed characters, since they are so prevalent in many types of attacks: SQL injection, XSS, PHP/Javascript RCE... I think PL4 is a good level to block this. They have a big chance of causing false positives though, but I think when running in PL4 you probably have to create exclusions for almost all input fields.

At the other hand, I think `@` is more in a grey area. It has special meanings in some contexts, although I can't think of a example. It's used in SQL but I don't think you can construct an attack solely with this character. So, I would not object to add `@` to allowed characters, unless somebody can give an example of an attack depending on `@`?

**Comment by dune73** [comment]
I second @lifeforms' opinion here. 

As for `@`: It's role in the DOM model gives it a role in many XSS exploits. See https://portswigger.net/web-security/cross-site-scripting/cheat-sheet

**Comment by franbuehler** [comment]
Ok, thank you very much for your opinions!

So: 

- Adding `(`, `)` and `@` -> better not
- Adding `Sec-CH-UA`: probably yes

Would that make sense?

**Comment by dune73** [comment]
I think that would be a good way forward.

920274 is like the last resort. If this rule turns blind, we're defeated. So better be very cautious, but the exclusion for the additional header makes sense to me.

**Comment by franbuehler** [comment]
Ok, thank you both! I'll open a PR.

**Comment by fzipi** [comment]
This one can be closed after merging.
