### ISSUE TITLE
Issue with false positive by UPS ccess point module (magento 2)

### ISSUE THREAD

**Issue by achatpc** [coreruleset/coreruleset#2403]
### Description

```
Feb 22 06:27:26.951263 2022] [:error] [pid 1307136:tid 139892419966720] [client 91.181.*.*:62137] [client 91.181.*.*] ModSecurity: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/etc/modsecurity/rules/RESPONSE-980-CORRELATION.conf"] [line "91"] [id "980130"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 5 - SQLI=0,XSS=0,RFI=5,LFI=0,RCE=0,PHPI=0,HTTP=0,SESS=0): individual paranoia level scores: 5, 0, 0, 0"] [ver "OWASP_CRS/3.3.2"] [tag "event-correlation"] [hostname "www.achatpc.com"] [uri "/fr/upsap/index/locator"] [unique_id "YhR0Pm8evuYSLiQEVU4LTAAXpD4"], referer: https://www.achatpc.com/fr/checkout/
```

### Audit Logs / Triggered Rule Numbers

Rules 980130 949110 930120

### Your Environment

Ubuntu 20.04, apache 2.4, Magento 2.4

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):
* Web Server and version (e.g., apache 2.4.41):
* Operating System and version:
CRS 3.3.2
### Confirmation

[* ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by achatpc** [comment]
I have try this in .httaccess file but not work. I think my syntax is incorrect.

<IfModule mod_security.c>
  <If "%{REQUEST_URI} =~ ~ m#/upsap/#">
    SecRuleRemoveById 930130
  </If>
</IfModule>

All help and suggession are welcome.

Thank you in advance for help.

**Comment by airween** [comment]
Hi @achatpc,

I'm afraid we can't help till you give us more details about your issue. You forgot to provide important snippets in your first comment, especially:

* CRS version (e.g., v3.2.0):
* Paranoia level setting:
* ModSecurity version (e.g., 2.9.3):

Also we need the error/audit log with more details. Based on the given information, we can't decide which rules triggered exactly and why. Some rules what you provided are not blocked the request, just increases the anomaly score. Until we don't see why increased the anomaly scoring, we can't help.

These are the rules (in CRS 3.3/master) what you wrote above:

* [930120](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf#L78-L97)
  * this rule uses this [data](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/lfi-os-files.data) file
* [949110](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-949-BLOCKING-EVALUATION.conf#L80-L93)
* [980130](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/RESPONSE-980-CORRELATION.conf#L82-L91)

In your second post you mentioned rule [930130](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf#L105-L124), which also depends on a [data](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/restricted-files.data) file. But I don't see the reason, why have you removed from your execution chain.

Please provide your details (above) and more relevant log parts.

ps: I've reformatted your posts, because the Apache config wasn't visible, and the log lines are better highlighted now. Use the sequence of ``` to do the same.

**Comment by dune73** [comment]
We have not heard from @achatpc about the additional details that @airween requested. Closing this.
