### ISSUE TITLE
Is there a PL0 rules set?

### ISSUE THREAD

**Issue by liudongmiao** [coreruleset/coreruleset#2424]
### Motivation

It's hard for new users to handle `false positive`, even we choose PL1, there are many `false positive`.

### Proposed solution

Introduce a very basic PL0 rules, only include **dangerous** rules.

### Additional context

Nemesida WAF team has a waf_bypass tool: https://github.com/nemesida-waf/waf-bypass
With PL1, there are about 45% passed (55% failed).

And I have test waf_bypass with cloudflare, its about 100% (except ua).

**Comment by dune73** [comment]
There is no PL0. We have been talking about this before, but nothing really done so far.

From my perspective there are two main reasons so far:
* PL1 can be bypassed fairly easily. PL0 would be even easier and it could damage our brand.
* One of the biggest sources for FPs these days is 942100. It is also a very, very imporant rule for anything SQLi and on top, we do not control it since it's a 3rd party library (that is no longer maintained).

So if we do a PL0, we water it down to a level where you get hardly any security benefit at all anymore.

What is possible though, and I think we might actually welcome that, would be a 3rd party PL0 plugin. That would be a generic rule exclusion plugin that simply removes rules from CRS. That would be very easy to do, it would be non-official and it still supports your use case.

Leaving this issue open for the time being so we can continue the conversation, but official support for a PL0 is unlikely.

**Comment by azurit** [comment]
@liudongmiao Can you tell more about false positives you encountered? Like, what software are you running on your web?
