### ISSUE TITLE
Work through list of SQLi bypasses submitted by Shivam Bathla

### ISSUE THREAD

**Issue by dune73** [coreruleset/coreruleset#2626]
### Description

See the following spreadsheet:
*  https://docs.google.com/spreadsheets/d/1OF6vt-YQRH7Vxmemp9QGrsEYWNvQ29zJZzGTl63faik/edit#gid=0

(Only visible for CRS team.)

### Your Environment

Irrelevant

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by franbuehler** [comment]
This is next on my todo list!

**Comment by franbuehler** [comment]
I think by resolving all issues and merging all PRs with label [sqli-bypass-bathla](https://github.com/coreruleset/coreruleset/issues?q=label%3Asqli-bypass-bathla+created%3A%3C2022-11-02+) this issue is resolved.

Details about the bypasses and my work sheet with the decisions can be found on our CRS share in the folder "Security 2022".
