### ISSUE TITLE
Add blocking mode for CRS Sandbox

### ISSUE THREAD

**Issue by studersi** [coreruleset/coreruleset#2658]
### Motivation

Currently, the sandbox never blocks: https://coreruleset.org/docs/development/sandbox/#example
> The sandbox will return a 200 response code, no matter if an attack was detected or not.

This can be confusing for tools that benchmark or compare WAF configurations:
* How does my configuration compare to vanilla CRS?
* How does WAF X compare to CRS?

### Proposed solution

It would be great if this behaviour could be dynamically changed per request by adding headers. Similar options to control the behaviour of the sandbox are already configurable using headers: https://coreruleset.org/docs/development/sandbox/#changing-options.

Useful options could be:
* Blocking/Detection
* Anomaly Threshold

### Alternatives

--

### Additional context

One tool that could be interesting with respect to the sandbox is [GoTestWAF](https://github.com/wallarm/gotestwaf). This tool provides an option that might help circumvent the problem but I have not got it to wor yet:
```
--blockRegex string      Regex to detect a blocking page with the same HTTP response status code as a not blocked request
```

FYI: @roguelabs

**Comment by dune73** [comment]
Interesting thought. Thanks.

**Comment by fzipi** [comment]
Thanks @studersi , we have an open ticket for this in the sandbox repo, but still didn't manage to allocate the time.

One thing that is not going to work, imho, is that we cannot dynamically change the anomaly threshold. This will imply:
- we need to reconfigure and reload the waf, dynamically, from the frontend (error prone, time consuming, etc.)
- we need to create a new dynamic waf for each request, depending on the anomaly threshold requested. And then kill it. This is a nightmare on dynamic launches on containers, etc.

I don't see us doing that. For now, we are targeting just passing a header that will return the proper status code.

**Comment by studersi** [comment]
@fzipi Thanks for the info but I am not sure I understand why this could not be done at runtime. Shouldn't it be possible to create a MosSec rule that looks at the header and changes the variable holding the threshold?

**Comment by dune73** [comment]
I agree with @studersi. We currently use `X-CRS-Paranoia-Level` to assign a PL per request. The anomaly thresholds are another two values that we can easily set dynamically.

What would happen is that the backend would block and the Sandbox proxy in front would have to handle the 403 similarly to the 200. I think that should work.

If it does not, then things could get hairy and then maybe the sandbox proxy would need to do the 403 after receiving a 200 from the backend and a notice via a http response. That would be cumbersome though, since all backends would have to support thiscustombehaviour (-> notice via header).

**Comment by fzipi** [comment]
Oh, I see it now. I was only thinking on the docker variables side, but then of course those variables are for setting up the rules, so we can always change them from the rules side.

Will try to figure it out using this now.

**Comment by fzipi** [comment]
@studersi Ok, I've implemented the first option using the new header `x-crs-mode: blocking`. Anything else will keep mode in `DetectionOnly`. Do you want to use the new v4 naming for this?

**Comment by fzipi** [comment]
For the other part, I'm adding this config:
```
curl -H "x-crs-inbound-anomaly-score: 10" "http://sandbox.coreruleset.org/"
curl -H "x-crs-outbound-anomaly-score: 10" "http://sandbox.coreruleset.org/"
```
But I'm wondering now if I've placed them in the correct place. Tests look good, but will do further testing.

**Comment by fzipi** [comment]
I was being lazy 😄 

The rule changes the correct var, but didn't want to write all 🐢 

```
SecRule REQUEST_HEADERS:x-crs-inbound-anomaly-score  "@gt 0" \
  "id:100030,phase:1,nolog,pass,\
  setvar:'tx.inbound_anomaly_score_threshold=%{MATCHED_VAR}'"
```

So you prefer to change it to `x-crs-(in|out)bound-anomaly-score-threshold` instead? 😉

**Comment by dune73** [comment]
I think that's the way to go.

And then we ought to think about whether we want to have 5 as default as with CRS.

**Comment by fzipi** [comment]
Why change defaults? You can select everything now, both PL and threshold. I would stick to PL1 and 5/4 as usual. If the users needs anything different, they can go for "header as a service" mode 🤣

**Comment by dune73** [comment]
I meant status 403 at default threshold of 5 reached. Since this is what people kind of expect.

**Comment by studersi** [comment]
> Let me re-phrase my question then: Should we make `x-crs-mode: blocking` the default?

Good question. Ithink that would be more intuitive and we can always disable it explicitly where needed (e.g. for regression tests).

**Comment by fzipi** [comment]
We have three different use cases:

- if we are doing simple `curl`s, where you want a quick answer, and you don't care about http status code, it doesn't matter
- if you are automating, then you can set the headers as needed, so it doesn't matter
- when we provide the sandbox for BB testers that are doing manual test against real vulnerable web applications. This case might be very disruptive for them

I think the last one is the problem. Adding headers in a browser might not be that simple, and we want to be easy to use, so I would say we don't block for now?

**Comment by dune73** [comment]
I see a 4th user case: Potential users that want to try out CRS with a pen-test report in their hand.

And I do not see how your 3rd use case is affected. Why is a researcher tester affected when a request is being blocked when it's malicious?

**Comment by fzipi** [comment]
It was one of the things that we heard about while at the BB. Some flows were trying stuff and not blocking was a requirement.

But then we are the owners and we can decide what we are providing from now on.

**Comment by dune73** [comment]
Got you. So these are the 4 use cases:

1 - developer running curl to get a quick answer; this is about the rules, status code behavior irrelevant,
2 - script or agent doing tests; can be configured to set the right headers
3 - security researcher / bug bounty hunter using an vuln application or a challenge; blocking the flow via forbidden status code can be annoying
4 - newbie or potential user who wants to try out a certain payload to learn whether CRS would detect and block it; non-blocking behavior could be hard to understand.

Use case 3 and use case 4 are contradicting.

Yet with providing bounty hunters with individual challenges instead of a vulnerable application, I think we can pay attention to their needs. And even if setting a default header in the browser is cumbersome, it's easier than to make sure a non-CRS user understands that a response of 200 can still indicate CRS would block in production.

So I tend to think we should prioritize scenario 4 over 3.

On top: We can do different defaults for different URIs if it is really needed. Even if this complicates things a bit.

**Comment by fzipi** [comment]
The decision from the meeting yesterday is to change the default mode on the sandbox to blocking.

**Comment by dune73** [comment]
Argh, this was the issue with the relevant comments I could not find again last night. Did not remember it was in the main repo.

Either way, given this is not implemented and the new default, I think we can close this. Correct?

**Comment by fzipi** [comment]
This is implemented, but not merged yet.

**Comment by dune73** [comment]
Yes, but I'd still close in favor of the new PR.

**Comment by aspiers** [comment]
Please can someone point to where was the implementation / PR for this?

**Comment by fzipi** [comment]
Hi @aspiers! We have the crs sandbox code in a private repo, sadly. We planned to opening it, but we didn't had the time to do cleanup and be really sure that we are not giving it to attackers...

If you are really interested, let's see what can we do.

**Comment by aspiers** [comment]
Hi @fzipi, thanks for the quick reply! No problem, I don't really need to see any such PR - I was just hoping to figure out an explanation for #3609, but probably you can provide one anyway :)
