### ISSUE TITLE
\xc5\xbc --> Polish 'ż' character blocked

### ISSUE THREAD

**Issue by bzc0fq** [coreruleset/coreruleset#2852]
### Description
When I POST a text including even one Polish 'ż' (HTML formatted UTF-8 \xc5\xbc) character (there can be more) it gets blocked.
It should not be blocked since 'ż' is basic/widely used character.

### Audit Logs / Triggered Rule Numbers

`/var/log/httpd/modsec_audit.log` looks like this:

``
Message: Warning. Pattern match "\\xbc[^\\xbe>]*[\\xbe>]|<[^\\xbe]*\\xbe" at ARGS:opis. [file "/etc/httpd/modsecurity.d/activated_rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "546"] [id "941310"] [msg "US-ASCII Malformed Encoding XSS Filter - Attack Detected"] [data "Matched Data: \xbc<br> found within ARGS:opis: \xc5\xbc<br>"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-tomcat"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"]
``

``
Message: Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "93"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"]
``

``
Message: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules/RESPONSE-980-CORRELATION.conf"] [line "91"] [id "980130"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 5 - SQLI=0,XSS=5,RFI=0,LFI=0,RCE=0,PHPI=0,HTTP=0,SESS=0): individual paranoia level scores: 5, 0, 0, 0"] [ver "OWASP_CRS/3.3.0"] [tag "event-correlation"]
``

### Your Environment

* CRS version 3.3.0:
* Paranoia level setting: I'm not sure of this... I guess 1, since this is a default one and I did not set it by myself.
* ModSecurity version 2.9.2:
* Web Server and version apache 2.4.37:
* Operating System and version: Rocky Linux 8.6

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
@bzc0fq Hi and thanks for reporting this!

Can you be so kind and provide us with a curl command which is triggering this problem on our sanbox? I tried this but it doesn't work:
```
$ curl -i -H "x-format-output: txt-matched-rules" -H "x-backend: apache" -H "x-crs-version: nightly" -H "x-crs-paranoia-level: 1" "https://sandbox.coreruleset.org/" --data-urlencode 'a=ż'
HTTP/1.1 200 OK
Date: Sun, 16 Oct 2022 08:29:53 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
X-Unique-ID: Y0vBAVbxxhgPnh0H7yTdZQAAAJQ
x-backend: apache-nightly
```
Thank you!

**Comment by bzc0fq** [comment]
here it is... 
curl 'https://somehost.pl/somescript.php' -X POST -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0' -H 'Accept: */*' -H 'Accept-Language: pl,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://somehost.pl' -H 'Authorization: Basic bWFyZWsubWF6b25AZ21haWwuY29tOk15c2l1cmthMTIzPw==' -H 'Connection: keep-alive' -H 'Referer: https://somehost.pl/somescript.php' -H 'Cookie: lastActivePatient=U2FsdGVkX1/KG2pPgQvMFeSULuSF9DXVGnZgtVzkdlpPQUvTBVqH7SY9VjoCP2ll; lastActiveTab=4; PHPSESSID=st4pf02atlorsa4ssf2jjpj727' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw 'nazwaPotrawy=test&opis=%C5%BC%3Cbr%3E&komentarz=&cbEPoESniadanie1=true&cbEPoESniadanie2=true&cbEPoEObiad=false&cbEPoEPodwieczorek=false&cbEPoEKolacja=true&cbEPoEPrzystawka=false&cbEPoELunch=false&cbEPoEDeser=false&cbEPoEPrzekaska=false&cbEPoEObiadokolacja=true&cbEPoEBezglutenowy=false&cbEPoENiskiIG=false&cbEPoELekkostrawna=false&cbEPoEWegetarianska=true&cbEPoEWeganska=true&cbEPoENiskoweglowodanowa=false&cbEPoENiskokaloryczna=false&cbEPoEBezmleczna=false&items%5B0%5D%5BnazwaProduktu%5D=bu%C5%82ka+pszenna&items%5B0%5D%5Bwaga%5D=80&items%5B0%5D%5BmiaraOpisowa%5D=sztuka&items%5B0%5D%5BwagaOpisowa%5D=80&items%5B0%5D%5BiloscOpisowa%5D=1&items%5B0%5D%5Bkomentarz%5D='

**Comment by bzc0fq** [comment]
I am not sure I have created this output right, if not please let me know how to do this... what I did was copping cUrl from firefox/netowork/... cURL ... I hope this will work for you :)

**Comment by RedXanadu** [comment]
Hi @bzc0fq!

Good news: we've already fixed this issue! The same problem was reported for Cyrillic characters in issue #1942 back in 2020. (Fixed in PR #2107).

Two potential solutions for you:

- You could write a rule exclusion for the false positive you're experiencing: see our official documentation on this subject, [here](https://coreruleset.org/docs/concepts/false_positives_tuning/).
- You could backport the fixed version of rule 941310 from our development branch into your v3.3.0 rule set, if you're confident in doing that.

### Note:

**v3.3.0 is no longer considered to be secure.** There are known vulnerabilities affecting this version, and it is no longer supported. You should seriously consider updating to the most recent minor release of the 3.3.x line, which is v3.3.4.

You should also seriously consider updating to the latest version of ModSecurity (v2.9.6) and updating your `modsecurity.conf-recommended` rules for the same reason.

More details: [here](https://coreruleset.org/20210630/cve-2021-35368-crs-request-body-bypass/), [here](https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-dos-vulnerability-in-json-parsing-cve-2021-42717/), [here](https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/), and [here](https://coreruleset.org/20220920/crs-version-3-3-4-and-3-2-3/).

**Comment by bzc0fq** [comment]
Thank you for the information... l was looking for 3.3.4 for el8 but, it is not available yet.

**Comment by RedXanadu** [comment]
@bzc0fq I can't find any modern CRS releases available as RPMs. I'm not sure who in the CentOS/RHEL community takes care of creating CRS RPMs.

The Core Rule Set is essentially just a collection of text files. CRS is architecture and distribution agnostic. I'd recommend untying yourself from distribution packages and instead using our [official releases](https://github.com/coreruleset/coreruleset/releases).

I'm going to mark this issue as closed, now, but feel free to reply if you have any follow-on questions. Thank you!
