### ISSUE TITLE
Failure on triggering rule 920400 with test 920400-1

### ISSUE THREAD

**Issue by M4tteoP** [coreruleset/coreruleset#2876]
### Describe the bug
I have some problems triggering the rule [`920400`](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L879) running the regression test [`920400-1`](https://github.com/coreruleset/coreruleset/blob/2813c610d8115592c4a54272efa10f7f2e4da026/tests/regression/tests/REQUEST-920-PROTOCOL-ENFORCEMENT/920400.yaml#L8).
I think this happens because by default `tx.max_file_size` is not set (Rule `900340` is commented in [crs-setup.conf.example](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/crs-setup.conf.example#L607-L617)).

Could it be okay to add `setvar:tx. max_file_size= 1048576` to the [requirements rule](https://github.com/coreruleset/coreruleset/tree/v4.0/dev/tests/regression#requirements) of the regression tests just like is already done for `setvar:tx.combined_file_sizes`?

### Your Environment

* CRS version (e.g., v3.2.0): CRS v4.0/dev
* Paranoia level setting: PL4
* Coraza
* Envoy v1.23

I guess this problem originated because Envoy is not refusing the request like (according to the comments of the test) most web servers do, therefore I'm trying to really trigger the rule and not just expect an error because of the invalid request.

Thanks!

**Comment by franbuehler** [comment]
Hi @M4tteoP!

Thank you for reporting your problem and clearly documenting the issue.

It could actually be because Envoy doesn't seem to consider the request as invalid.
When I run the test 920400-1 locally against Apache, I get a "400 Bad Request" and the test actually fails. 
But that's ok because of `expect_error: true` in the test, as you wrote above.

I don't have a Coraza running locally (unfortunately not yet). 

Have you been able to test successfully it after setting the variable with `setvar:tx. max_file_size= 1048576`?
If it works for you, I think we might add this to the requirements, like you proposed.

**Comment by M4tteoP** [comment]
Hi @franbuehler, thank you!
I confirm that setting `tx. max_file_size` leads to successfully triggering the rule. So it would be great to add it to the requirements.

Stil, the test will not pass (just against Envoy) because the output should become `log_contains` instead of `expect_error`. About that, what would you think about refactoring this test just like https://github.com/coreruleset/coreruleset/pull/2285? It would effectively test the rule with a valid request and add a negative test. Wrote a little attempt here https://github.com/coreruleset/coreruleset/pull/2877.

Thank you for any feedback!

**Comment by franbuehler** [comment]
That's good to hear. Thank you for testing. And thank you for providing a PR. That's great!
