### ISSUE TITLE
FP on CloudFlare __cf_bm cookies.

### ISSUE THREAD

**Issue by wpkc** [coreruleset/coreruleset#2879]
``SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|
REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/* 
"(?i)([\s\"'`;\/0-9\=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on(?:pointer(?:(?:lea|mo)ve|
o(?:ver|ut)|cancel|enter|down|up)|s(?:(?:elec(?:tstar)?|ubmi)t|croll)|
c(?:l(?:ick|ose)|ontextmenu|hange)|mouse(?:o(?:ver|ut)|down|move|up)|
touch(?:cancel|start|move)|key(?:press|down|up)|(?:abor|inpu)t|
(?:erro|blu)r|res(?:ize|et)|dblclick|focus|load)[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=)" \
        "msg:'XSS Filter - Category 2: Event Handler Vector',\
        id:941120,\
        ...``

Originally posted by @franbuehler in https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/675#issuecomment-290208352

Hi @franbuehler,

The above suggestion looked good to me.  But what got merged was an overly broad on[a-zA-Z]+ instead of listing each event explicitly.   At least once per month I am seeing legitimate CloudFlare bot management cookie content with an "on" or "ON" followed by one or more a-z or A-Z letters and finally ending in "==" .  Legitimate traffic is getting blocked.

Once this rule is fixed, I would also suggest removing !REQUEST_COOKIES:/__utm/ from the target list, since this just opens a hole in the rule for hackers to exploit; simply place a XSS hack inside a __utm cookie.

As a workaround, I ended up adding...
```
SecRuleUpdateTargetById 941120 "!REQUEST_COOKIES:/__cf_bm/"
```
But this just opens another hole in the rule, although it is harder to exploit when using CloudFlare then it would be to exploit the __utm hole.

Thanks.

**Comment by wpkc** [comment]
Here is a log file sample...

```
Message: Warning. Pattern match “(?i)[\\s\”‘`;\\/0-9=\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]on[a-zA-Z]+[\\s\\x0B\\x09\\x0C\\x3B\\x2C\\x28\\x3B]*?=” at REQUEST_COOKIES:__cf_bm. [file “/usr/share/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf”] [line “110”] [id “941120”] [msg “XSS Filter – Category 2: Event Handler Vector”] [data “Matched Data: 0ONw= found within REQUEST_COOKIES:__cf_bm: QY_91EOouIrhDolAZvcUI0Jb2yrdt1TFOa.y69fIH6Q-1666376704-0-AaILeMr88IaU17kL hM4VZS 1D4xyrSyJCn LHK4LZ2FCY9dOVz9sFGS4bm20zBci6/bIVNuJFn1bCa1dMqLSKosLh2hH eY1PQbJyOZog5fl0gZ3KhZ0We6qKFhcC0ONw==”] [severity “CRITICAL”] [ver “OWASP_CRS/3.3.0”] [tag “application-multi”] [tag “language-multi”] [tag “platform-multi”] [tag “attack-xss”] [tag “paranoia-level/1”] [tag “OWASP_CRS”] [tag “capec/1000/152/242”]
```

**Comment by franbuehler** [comment]
Thank you for reporting. I'll take a look.

**Comment by franbuehler** [comment]
To resolve FP with rule 941120 I [proposed](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/675#issuecomment-290208352) to explicitly list all (currently known) events. But in 2017 the project [decided](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/675#issuecomment-291244519) to not use this list but to use `on[a-zA-Z]+` instead of `on\w+`. 
In CRS 4.0 this rule 941120 will be moved to PL2 because FP are still likely. See [this commit](https://github.com/coreruleset/coreruleset/commit/8ea34d8d357a6715978b85e9c00aa909e7925590).
This means: for CRS 4.0 we'll have a list of know event handlers in rule [941160](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L156) at PL1 and a more generic rule [941120](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf#L760) that is more prone to FP at PL2.
I think that makes sense. But other opinions welcome.

So much for the rule itself.


Now we come to the cookies...

**Comment by wpkc** [comment]
Yes, I think the `[^=]` on the end of the regex will prevent an FP for CloudFlare __cf_bm cookies since the last bit of cookie data appears to be base64 encoded data that will always end in `==`

Thanks!

**Comment by franbuehler** [comment]
Great to hear! Thank you for the confirmation.
