### ISSUE TITLE
False positive: detected XSS using libinjection (REQUEST-941-APPLICATION-ATTACK-XSS.conf) - need of allow list for trusted domains

### ISSUE THREAD

**Issue by nitschSB** [coreruleset/coreruleset#3044]
### Description

Hello for us this is a false positive. It's a big multi (sub-) domain application. We would like to put them on a global allow list. Is this somehow possible?

### Audit Logs / Triggered Rule Numbers

The 941100 Rule got triggered.

``
[Mon Dec 05 x:x:x.x x] [:error] [pid x] [client x.x.x.x:x] [client x.x.x.x] ModSecurity: Warning. detected XSS using libinjection. [file "/somewhere/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "56"] [id "941100"] [msg "XSS Attack Detected via libinjection"] [data "Matched Data: XSS data found within ARGS:someUrl: [https://this-is-ok.com/something?someId=123]"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.4"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "hostname.com"] [uri "/path/"] [unique_id "xxxxx_xxxxxxxxxxxxxxxxxx"], referer: [https://hostname.com/path?someUrl=https%3A%2F%2Fthis-is-ok.com%2Fsomething%3FsomeId%3D123]
``

### Your Environment

* CRS version (e.g., v3.2.0): v3.3.4
* Paranoia level setting: 1
* ModSecurity version (e.g., 2.9.3): 2.8.0-7.3.1
* Web Server and version (e.g., apache 2.4.41):  2.4.23-29.43.1
* Operating System and version: SLES 12 SP5

### Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theseion** [comment]
Yes, that's possible. We have documentation on how to handle rule exclusions here: https://coreruleset.org/docs/concepts/false_positives_tuning/#rule-exclusions.
In essence, you probably will want to write a new rule that matches a specific argument or URL segment / query argument and upon match, exclude 941100.
If you need to use a list, you could compare against a file with `@pmFromFile`, for example. This depends on how many entries your list will have and whether you can craft a regular expression that matches (if all the domains are different, then you'll definitely need a list, otherwise you can probably just match the root domain with a regular expression).

I'm closing the issue, since this is a question about tuning. The rule matches as expected, IMO. Feel free to reply in this thread if you have questions.

**Comment by nitschSB** [comment]
Hi @theseion,
thank you for the explanation. I read the rule exclusions part as well as the [Description of the Four Paranoia Levels](https://coreruleset.org/docs/concepts/paranoia_levels/#description-of-the-four-paranoia-levels). There someone wrote
> Please report any false positives encountered with a PL 1 system via GitHub.
That's why I reported the issue.

I think that we aren't alone with this issue and user defined tursted domain list would be a good improovment, but it could
be difficult to do safely.

We decided to turn off the rule for specific targets:
`SecRuleUpdateTargetById 941100 "!ARGS:someUrl"`

Cheers!

**Comment by theseion** [comment]
Yes, thanks for reporting! It is not always clear what should be considered a false positive. As for general exclusion of user defined domains, it's a nice idea but would, unfortunately, be pretty hard to get right. We would need to check every rule to see whether it should respect the exclusion or not and that highly depends on the target and can even depend on the environment.
