### ISSUE TITLE
Again about russian letters in Modsecurity rules

### ISSUE THREAD

**Issue by valeriy-l** [coreruleset/coreruleset#3073]
Hi there!
Can you help me find out solution.
I have Modsecurity v3.0.5. and CRS 3.3.2 installed on astralinux.
PL is 4.

I faced with many false positives on the sites with russian letters.
For example:

[data "ARGS:query=\xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2 \xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd \xd0\x98\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb8\xd1\x87"]

rule 920273 [msg "Invalid character in request (outside of very strict set)"]
rule 942460 [msg "Meta-Character Anomaly Detection Alert - Repetitive Non-Word Characters"]
rile 942432 [msg "Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)"]

That is Иванов Иван Иванович in russian

I have read many discussion threads here, and try solution:
change Unicode mapping to 1251, added to unicode mapping file missing strings

0410:c0 0411:c1 0412:c2 0413:c3 0414:c4 0415:c5 0416:c6 0417:c7 0418:c8 0419:c9 041a:ca 041b:cb 041c:cc 041d:cd 041e:ce 041f:cf 0420:d0 0421:d1 0422:d2 0423:d3 0424:d4 0425:d5 0426:d6 0427:d7 0428:d8 0429:d9 042a:da 042b:db 042c:dc 042d:dd 042e:de 042f:df 0430:e0 0431:e1 0432:e2 0433:e3 0434:e4 0435:e5 0436:e6 0437:e7 0438:e8 0439:e9 043a:ea 043b:eb 043c:ec 043d:ed 043e:ee 043f:ef 0440:f0 0441:f1 0442:f2 0443:f3 0444:f4 0445:f5 0446:f6 0447:f7 0448:f8 0449:f9 044a:fa 044b:fb 044c:fc 044d:fd 044e:fe 044f:ff 0401:a8 0451:b8

But I faced with false positive again and again.

It seems that CRS is absolutely not compatible with the non-latim alphabet.

Or do I make something wrong?

**Comment by RedXanadu** [comment]
Thanks for the report @valeriy-l. I will take a look and give you an answer soon.

**Comment by lifeforms** [comment]
Hi @valeriy-l , it's true that unfortunately ModSecurity does not work well in cyrillic.

What I can recommend though is run at a lower paranoia level. Paranoia level 4 is really, really strict, to the point of being almost infeasible unless you spend a LOT of time on tuning. If you want to have a good protection against currently known attacks, including many advanced attacks, then I usually advise PL2.

Unfortunately, then I guess you will still have problems, and you _might_ have to disable some of our rules. But, you will still have protection of all the other rules which is better than nothing.

Can you re-try setting your paranoia level to 2 and trying again to see what kind of rule hits you get?

**Comment by RedXanadu** [comment]
Hi @valeriy-l,

One thing I would add to the great answer above: the Core Rule Set contains a series of rules that _restrict the range of values that a byte is allowed to take_. Each paranoia level has its own range of allowed byte values. The allowed range becomes more restrictive with higher paranoia levels.

For example: with paranoia level 3 and above, all byte values above 126 are forbidden. Unless I'm mistaken, this means that you are **guaranteed** to encounter false positives when using multi-byte UTF-8 encoded characters in PL 3 and PL 4, because the leading byte will _always_ be something above 126.

If your web application accepts multi-byte UTF-8 characters as input then you will have to work harder to tune away false positives at paranoia level 3 and 4. As suggested above, paranoia level 2 is a great place to start.

**Comment by RedXanadu** [comment]
I'm closing this issue now. Please feel free to re-open it if you have any further questions, comments, or feedback.
