### ISSUE TITLE
CRS v3.x IP reputation blocks are errant when `EXECUTING_PARANOIA_LEVEL` is used

### ISSUE THREAD

**Issue by diablodale** [coreruleset/coreruleset#3079]
CRS v3.x + `EXECUTING_PARANOIA_LEVEL` + `do_reput_block=1` leads to incorrect ip blocking for some combinations.
This is due to logic in `REQUEST-913-SCANNER-DETECTION.conf` where it runs additional blocking rules for EXECUTING paranoia levels yet still errantly ip blocks all ~executing~ paranoia levels using `reput_block_flag=1`

The spirit of executing paranoia level is to trigger rules without incrementing actionable paranoia anomaly scores or causing immediate blocks/deny -- so that config and rules can be tested and tuned. `REQUEST-913-SCANNER-DETECTION.conf` uses throughout its rules EXECUTING paranoia for test logic and applies IP reputation blocks. This is against the spirit of executing's "no blocks/deny" and not what I (a sample group of one 😉) would expect.

CRS v4 removes this IP reputation code #2433, therefore this issue is for current v3.x users and any further work on the same.

### Your Environment Setup

* CRS version v3.3.2
* Paranoia level setting: 1
* Executing Paranoia level: 2 👀
* ModSecurity version: 2.9.3-1+deb10u1 amd64
* Web Server and version: Apache 2.4.38-3+deb10u8 amd64 
* Operating System and version: Docker container with Debian GNU/Linux 10 (buster) and host kernel 5.15.79.1

### Steps to reproduce

Code review is how I found it as I was adjusting some 999 SecRuleUpdateActionById's. This is the general flow...

1. Setup as above
2. In crs-setup.conf enable `tx.do_reput_block 1`, `tx.reput_block_duration 4500`, `SecCollectionTimeout 4500`
3. attack the http server with a scripting user-agent that matches rule 913101

### Expected behaviour

Nothing happens. The response should be served to the attacker.

### Actual behaviour

The attacker is blocked and its IP address is added to the IP reputation blocklist.

### Additional context

The errant logic is throughout the file. One example is code like...

https://github.com/coreruleset/coreruleset/blob/18703f1bc47e9c4ec4096853d5fb4e2a204a07a2/rules/REQUEST-913-SCANNER-DETECTION.conf#L105-L106

Those skips will not be executed. This leads to the rule 913101 to be run.

https://github.com/coreruleset/coreruleset/blob/18703f1bc47e9c4ec4096853d5fb4e2a204a07a2/rules/REQUEST-913-SCANNER-DETECTION.conf#L121-L142

Line 139 increments the PL2 score. Which has no practical effect since setup is paranoia level=1.
Lines 140-142 put the IP address into the blocklist and ip reputation blocks.
The intention was likely to only ip rep block when `paranoia level >= 2`.
But the logic instead codes ip rep block for `executing paranoia level >=2`.

**Comment by RedXanadu** [comment]
Hi @diablodale. Thanks for the report. I will take a quick look over the weekend.

As you say, the IP reputation code has now been removed for the next major release. To be frank, I'm not sure how much enthusiasm there would be to continue to continue maintaining it, but maybe someone will step up to do so (or maybe it will be a case of "you must use the plugin going forwards", I guess we'll see.)

**Comment by RedXanadu** [comment]
Hi again @diablodale.

I've spent some time this evening having a proper look at this report. You've uncovered some interesting behaviour! Quite possibly, no one else has ever encountered this corner case.

**Summary for the benefit of other CRS developers:**
In 3.x, we have PL 2 rules in `REQUEST-913-SCANNER-DETECTION.conf` that use `setvar` to set a blocking flag. In `REQUEST-910-IP-REPUTATION.conf` there's a PL 1 rule that checks for that flag and adds a `CRITICAL` score to the PL 1 anomaly score. So, if your blocking PL is PL 1 but you have your executing PL as PL 2 or higher then a "detection only" PL 2 rule can cause a real block.

**If we want to fix this**, two ideas spring to mind:

1. Have two separate blocking flags: a PL 1 blocking flag and a PL 2 blocking flag. Check them and action them only if an appropriate blocking PL is in effect.
2. *(Easier solution)* Check the *blocking PL* when setting the blocking flag. Add a chain rule test: if blocking PL >= 2 then go ahead and set the blocking flag for the PL 2 rule. Otherwise, we're only executing the PL 2 rule because we have a higher executing PL, so don't flag because we mustn't block.

I think fully fixing, testing, and verifying this would be more time and effort than it's worth, but the issue has now been explored in this thread along with potential solutions for users to implement if they fall into this corner case.

**Comment by RedXanadu** [comment]
Flagged for January's 'project issues chat': do we have anyone who wants to fix this, or do we flag as *Won't fix*?

**Comment by diablodale** [comment]
I've got enough working knowledge to be dangerous 😉, though the errant behavior is actually what I *want* on my service...I want to aggressively deny+ip_rep them using modsec+crs (a single service for me to admin/maintain). Fixing the rules to match *expected* behavior is low-pri for me as it is opposite my service's needs and therefore adds work to undo the fix on my service.

Add to that CRS is focused on v4, I suggest this is a low-priority. And to just keep it documented for those that use v3, IP-rep, and executing_paranoia higher than paranoia level.

**Comment by dune73** [comment]
Thanks @RedXanadu, I think we're covered for CRS4 since I am still working on the replacement of the set of scanner detection rules. Simplification being one of the goals. But nice find indeed.
