### ISSUE TITLE
Consider deprecating use of ARGS and ARGS_NAMES

### ISSUE THREAD

**Issue by anuraaga** [coreruleset/coreruleset#3087]
Some context in https://github.com/corazawaf/coraza/pull/565

CRS currently uses 5 phases

1: Request headers
2: Request body
3: Response headers
4: Response body
5: Done

However, currently most rules are defined in a way that phase 1 and 3 are not actually usable - for example, this rule is evaluated at phase 2

https://github.com/coreruleset/coreruleset/blob/ed32dafa2114d34ed9280fbd1a3bc7d7d4e21fe4/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L46

But refers to things like `REQUEST_HEADERS` and `ARGS` - even if there is SQL injection in one of those, it will not be detected at phase 1 but at phase 2. This means phase 1 does not really provide protection from SQL injection, and in a broader sense can be considered not providing general OWASP protection by missing out on many important rules.

In Coraza, we are considering adding a mode that will evaluate rules in multiple phases - phase 1 variables are checked in phase 1, phase 2 variables are checked in phase 2. In this case it would allow the headers, cookies to be checked in phase 1 and XML in phase 2.

There are just two HTTP variables that cause problems with this - ARGS and ARGS_NAMES. This is because they concatenate GET and POST information, so they mutate between phase 1 and phase 2. To avoid double-evaluating, we must still execute these at phase 2. This means that for the example rule, even with multiphase evaluation, if the URL query parameters contain SQL injection, it won't be caught at phase 1 because those are matched with ARGS.

It is relatively simple to use immutable variables in such rules - just replace ARGS with ARGS_GET|ARGS_POST and similar for names. I propose this should be the practice in CRS and remove usage of the mutable variables - the change seems minor and it ensures that all information is using information with a easy-to-reason about lifecycle. And this enables new protection / optimizations such as the multiphase evaluation. While we could consider that CRS itself should split the example rule into two, one for phase 1 and one for phase 2, this would be a huge change to CRS, and likely would need new syntax for multiphase within a single rule to be maintainable rather than literally splitting rules. Just removing ARGS and ARGS_NAMES would be quite enabling though and simple.

**Comment by azurit** [comment]
Hi @anuraaga, I see your point and it makes sense to me. Anyway, we need to think deeply about consequences and discuss it internally.

**Comment by azurit** [comment]
I added this to Monthly Chat Agent for January (2nd Meeting).

**Comment by dune73** [comment]
Added my thoughts to https://github.com/corazawaf/coraza/pull/565#issuecomment-1379969525

**Comment by fzipi** [comment]
I would say also that CRS uses the phases that historically ModSecurity provided. Phase 5 is also `log` phase.

ModSecurity was originally very specific to Apache hooks: the places where the actual module was able to hook itself to perform access control. With connectors things are a bit more complex. Also having only five phases is just a coincidence: why not more or less? (we discussed this in Coraza some time ago).

The solution is not straightforward. If we want rules to only target specific phases, we need to decouple everything and have multiple rules that will target each phase. IMHO, this is not as crazy as it sounds. It will give optimal results. But then we need to do a new major release because everything must change to accommodate this. Maybe for v5?

**Comment by dune73** [comment]
I think this is a worthwhile discussion.

But you are a bit too quick for me in your last paragraph. Could you elaborate this some more, please?

**Comment by fzipi** [comment]
In the proposed example, we have these variables:
`REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/*`

If we move from ARGS to ARGS_GET and ARGS_POST, we would be able to simply split the rule in two, one for phase 1 with all the stuff that affect headers only:
`REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_GET|ARGS_GET_NAMES`
and an equivalent phase 2 rule (twin rule?), only using
`ARGS_POST|ARGS_POST_NAMES|XML:/*`.

This way we use specific variables per phase.

**Comment by fzipi** [comment]
We have 157 rules where we use `ARGS`.

**Comment by dune73** [comment]
Got you. Thanks.

**Comment by RedXanadu** [comment]
If I understand this correctly:

> Just removing ARGS and ARGS_NAMES would be quite enabling though and simple.

in theory, the *minimal change* required by CRS would be to convert every instance of

`ARGS -> ARGS_GET|ARGS_POST`

and

`ARGS_NAMES -> ARGS_GET_NAMES|ARGS_POST_NAMES`

Making these changes would provide enough additional information to enable engines that do not respect the classical Apache-like phases (e.g. Coraza) to adjust their behaviour accordingly.

So, we don't need to take 157 `ARGS` rules and add 157 extra rules in phase 1. Adding 157 new rules would add significant overhead.

Is that correct, @anuraaga ?

**Comment by RedXanadu** [comment]
Thinking about it, if you pretend that

`ARGS_GET` has a more meaningful name like `QUERY_STRING_PARAMS`

and pretend that `ARGS_POST` is named something like `BODY_PARAMS`

then it seems appropriate that `QUERY_STRING_PARAMS` and `BODY_PARAMS` would be treated differently.

For example: if you could block a request early in phase 1 because it has a malicious query string parameter, why wait until phase 2 simply because you're waiting for form fields from a body or something? Maybe a change like this could improve early blocking functionality in the future?

**Comment by airween** [comment]
What do we want to do with some special rules, eg [920390](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L853-L872), where we check the length or (summarized) arguments?

**Comment by dune73** [comment]
OK, the CRS project talked this through in our meeting tonight, 2023-01-16. You can find the transcript and the decisions in our chat archive: https://github.com/coreruleset/project-chat-archive/blob/master/README.md

* We rule out the idea to split all rules engaging with headers / query string arguments and also with request body parameters into two separate copies of the same rule for performance reasons and because of the huge amount of work it would generate (separating tests to name but one problem).
* Splitting rules into two and allowing more rules to run in phase 1 and thus block more attacking requests at the end of phase 1 via early blocking is mostly irrelevant from a performance perspective, since all benign requests will have to run through all the rules in all the phases and the only thing we gain is the attackers getting their 403 a bit faster. (Plus less alerts in the logfile, which is a real plus, but only a small one).
* We have dynamic generation of rules on our roadmap. So a few years down the road, all CRS rules will be generated. Generating them in a way it accommodates Coraza/Envoy will be easy afterwards.
* We generally think that replacing ARGS with ARGS_GET/ARGS_POST etc. would not be too complicated. But we also think Coraza would be able to do that dynamically. So not really any strong opinions on that variant, but also little benefit for the change from a CRS perspective.
* Now there are a few CRS rules that are a bit more complicated, @airween mentioned 920390, 921170/80 are quite special too, and there are probably half a dozen friends. They would have to be rewritten and this could get hairy. So we think CRS would get more complicated for very little gain.
* We also think that Coraza should be able to replace ARGS with ARGS_GET/ARGS_POST dynamically where it makes sense. So you do not really, really need CRS to do this for you.
* Our conclusion is thus, that we will not take any action for the time being.

Sorry we do not have better news for you. Still, it just does not make sense to change our rules over this problem right now.

**Comment by dune73** [comment]
Let's keep the issue open for a few days, but unless we hear new arguments, we will close this.

**Comment by RedXanadu** [comment]
As agreed at the issues chat meeting on Monday 17 July, as we've already discussed and considered this proposal at length earlier in the year, and eventually decided not to move ahead with it, this issue can now be closed.
