### ISSUE TITLE
Monthly Chat Agenda April 2023 (2023-04-03 and 2022-04-17)

### ISSUE THREAD

**Issue by RedXanadu** [coreruleset/coreruleset#3159]
This is the Agenda for the two Monthly CRS Chats.

The general chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, 2023-04-03, at 20:30 CET. That's the 1st Monday of the month. A separate issue chat is happening at the same location, same time on Monday, 2022-04-17. That's the 3rd Monday of the month. Please note that we have a [CRS calendar](https://calendar.google.com/calendar/u/0/embed?src=c_glsll5etlmcb3it0k433fcl5rc@group.calendar.google.com) (maintained by @fzipi).

Archived previous meetings and their decision are [here](https://github.com/coreruleset/project-chat-archive/blob/master/README.md).

### Outside development

* :sunny: **Google Summer of Code (GSoC):** We provided the same projects we did last year for GSoC 2023, we still need to add the ones we decide to do at Varese 2022. ⏳ 
* Following the open letter to the OWASP board by several OWASP project leaders and two board members, new board member (and former OWASP co-founder) Mark Curphey left the board concluding the concerns and demands in the open letter were not addressed fast enough or in a systematic way. He shared ideas of launching a new organization, probably tighter and better funded one. CRS is observing the situation. (https://www.linkedin.com/pulse/yesterdays-owasp-board-directors-meeting-i-resigned-my-mark-curphey)

#### Rules

* PR's for FP's agains `sh` and `fi` in argument names and values (thanks to @Xhoenix, @emphazer)

#### CRS Sandbox

* The integration of the Coraza Playground has not started yet, but is right on top of the tasklist.

#### CRS Bug Bounty and Security

* See below under documentation
* Currently 4 security items open. Mostly solved.

#### Plugins

* Impressive work by contributor https://github.com/Xhoenix and @azurit on the Nextcloud rule exclusions plugin

#### Documentation and Public Relations

* :vhs: CRS Community Summit videos now on YouTube (with the audio sync fixed): https://www.youtube.com/@owaspmodsecuritycoreruleset
* :memo: Rewriting the `INSTALL` document continues but is very slow and very tedious work.
* Grand Bug Bounty Blog post is almost done; a 3rd party reviewer asked for a rewrite of a paragraph

#### Project Administration and Sponsor relationships

* There was a call with OWASP HQ to make accounting easier for us.
* Two sponsors indicated they are not sure they can continue with sponsoring us in 2023. But a new one is getting serious. We'll be fine, but it takes work.

#### Tools

* [rules-check.py](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/util/crs-rules-check/rules-check.py) script checks the commented `SecRule` and `SecAction` entries in [crs-setup.conf.example](https://github.com/coreruleset/coreruleset/blob/v4.0/dev/crs-setup.conf.example) by [#3161](https://github.com/coreruleset/coreruleset/pull/3161). Explicit initialization of the `TX` variable is no longer necessary if it exists in `crs-setup.conf.example`, with comments.
* go-ftw release 0.4.9 with improvments to overrides and cloud mode

#### Testing incl. Seaweed and many future plans

* No news in this front.

#### Containers

* :arrow_up_small: Updated Apache because of CVE-2023-25690 https://github.com/coreruleset/modsecurity-crs-docker/pull/132

#### CRS Status Page

* :test_tube: One new test added this month (#3158).

## Project discussions and decisions

* _curl User-Agent problem._
  Due to the recent ‘Unix command’ rule changes, if you use `curl` to access something through CRS then you get an anomaly score of 10 (5 at PL 2 + 5 at PL 3, 932236 PL2 and 932237 PL3) due to "curl" being detected in the User-Agent string. This seems like a significant change: compare this to CRS 3.3.x which does not penalise the use of `curl` at all.
  **Question:** Do we need to fix this? If so, who needs to do what to fix it?
* _Discuss C9K-230327._
  **Qs:** We are in agreement on our approach? Who will implement this?
  _Please be careful what we say on public channels about this at the present time._
* _Referer header headache._
  The Referer header was recently added to several rules to combat a series of bypasses. Unfortunately, some legitimate Referer headers now cause false positives with rule 932200 (issue: #3180).
  **Q:** It has been suggested to simply remove Referer from this rule because it is difficult to fix otherwise: are we happy with this?
* _Report of possible transformation bypass._
  It has been reported (#3182) that having `t:base64Decode` at the end of a transformation pipeline may allow for certain bypasses.
  I _think_ they might be suggesting that we need to perform an additional round of `t:urlDecodeUni,t:jsDecode,t:removeWhitespace` _after_ the Base64 decoding step?
  **Qs:** Do we:
  * a.) fully understand the reported issue (any further details required?), and
  * b.) agree with the reported issue?
  * Do we need to change all of our current (and future) rules to move `t:base64Decode` away from the end of all transformation pipelines?

### PRs that have been merged since the last meeting

* #3185
* #3171
* #3179
* #3177
* #3161
* #3175
* #3176
* #3155
* #3169
* #3166
* #3135
* #3157
* #3153

We merged 13 PRs since the last monthly project chat.

### Open PRs marked *DRAFT* or *work in progress* or *needs action*

* #3186
* #3187
* #3184
* #3141
* #3170
* #3167
* #3158
* #2637
* #2666
* #2878
* #3029

### Open issues and PRs

* As of Monday, we have 103 open issues.
* As of Monday, we have 20 open pull requests.

# Separate 2nd Meeting (Monday, 2022-04-17)

* PR #2878
* PR #2637 
* PR #2303
* PR #2302
* PR #2301
* PR #2217
* PR #3190 - about comments syntax between parts of a chained rule

## How to get to our slack and join the meeting?

If you are not yet on the OWASP Slack, here is your invite: https://owasp.org/slack/invite .

Everybody is welcome to join our community chat.

**Comment by franbuehler** [comment]
## Decisions 2023-04-03

* _curl User-Agent problem._
  Due to the recent ‘Unix command’ rule changes, if you use `curl` to access something through CRS then you get an anomaly score of 10 (5 at PL 2 + 5 at PL 3) due to "curl" being detected in the User-Agent string. This seems like a significant change: compare this to CRS 3.3.x which does not penalise the use of `curl` at all.
  **Question:** Do we need to fix this? If so, who needs to do what to fix it?
  **Decision:**
* _Discuss C9K-230327._
  **Qs:** We are in agreement on our approach? Who will implement this?
  _Please be careful what we say on public channels about this at the present time._
* _Referer header headache._
  The Referer header was recently added to several rules to combat a series of bypasses. Unfortunately, some legitimate Referer headers now cause false positives with rule 932200 (issue: #3180).
  **Q:** It has been suggested to simply remove Referer from this rule because it is difficult to fix otherwise: are we happy with this?
* _Report of possible transformation bypass._
  It has been reported (#3182) that having `t:base64Decode` at the end of a transformation pipeline may allow for certain bypasses.
  I _think_ they might be suggesting that we need to perform an additional round of `t:urlDecodeUni,t:jsDecode,t:removeWhitespace` _after_ the Base64 decoding step?
  **Qs:** Do we:
  * a.) fully understand the reported issue (any further details required?), and
  * b.) agree with the reported issue?
  * Do we need to change all of our current (and future) rules to move `t:base64Decode` away from the end of all transformation pipelines?
