### ISSUE TITLE
False positive response to Cyrillic characters in a string 

### ISSUE THREAD

**Issue by flexstat** [coreruleset/coreruleset#3178]
### Description

faced with a problem when such a fragment  "являются не" in Cyrillic is added to the feedback form, the 941120 rule is triggered, and the server gives the 403 code. 
how to fix the problem 

### Logs

``
2023/03/27 12:29:12 [warn] 3521#3521: *461 ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)[\s\"'`;/0-9=\x0B\x09\x0C\x3B\x2C\x28\x3B]on[a-zA-Z]{3,25}[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=[^=]' against variable `ARGS:message' (Value: `\xd1\x8f\xd0\xb2\xd0\xbb\xd1\x8f\xd1\x8e\xd1\x82\xd1\x81\xd1\x8f \xd0\xbd\xd0\xb5' ) [file "/opt/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "89"] [id "941120"] [rev ""] [msg "XSS Filter - Category 2: Event Handler Vector"] [data "Matched Data: ;ONBAO =5 found within ARGS:message: O2;ONBAO =5"] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "paranoia-level/2"] [tag "OWASP_CRS"] [tag "capec/1000/152/242"] [hostname "172.28.0.3"] [uri "/mail.php"] [unique_id "167992015240.544431"] [ref "o2,9v1577,21t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"], client: 172.28.0.2, server: www.example.com, request: "POST /mail.php HTTP/1.1", host: "site.ru", referrer: "http://site.ru"
``

``
mybunker_1  | 2023/03/27 12:29:12 [error] 3521#3521: *461 [client 172.28.0.2] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `5' ) [file "/opt/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "80"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "2"] [ver "OWASP_CRS/3.3.2"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "172.28.0.3"] [uri "/mail.php"] [unique_id "167992015240.544431"] [ref ""], client: 172.28.0.2, server: www.example.com, request: "POST /mail.php HTTP/1.1", host: "site.ru", referrer: "http://site.ru/"
``

### Your Environment

OWASP_CRS/3.3.2
(tag:'paranoia-level/2',\)
 ModSecurity version (e.g., 2.9.6):
 Operating System and version: ubuntu 22.04

**Comment by RedXanadu** [comment]
Hi,

Firstly, it appears that you're running CRS version 3.3.2. You should strongly consider updating to the latest stable release, which is v3.3.4, as that fixes several security vulnerabilities (see [here](https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/) and [here](https://coreruleset.org/20220920/crs-version-3-3-4-and-3-2-3/) for more information.)

Secondly, have you tuned the Core Rule Set for your web application? It looks like you're running with an inbound anomaly score threshold of 5, which is not a good idea unless you have completed the full tuning process - because otherwise you are highly likely to run into false positives like the one you've reported here!

Lastly, let's look at the false positive you've reported. Unfortunately, this is an example where a CRS rule can take valid UTF-8 and its anti-evasion transformations turn that UTF-8 into rubbish. The problem is that the transformed rubbish can sometimes trigger the rule, which is the case here:

```
Input: являются не
Transformation - UTF-8 to Unicode: "%u044f%u0432%u043b%u044f%u044e%u0442%u0441%u044f %u043d%u0435"
Transformation - Decode percent-encoded string and accept Microsoft %uXXXX variant: "O2;ONBAO =5"
```

`;ONBAO =5` looks a bit like `onload="alert(1)"` and matches the pattern of this particular anti-XSS rule.

---

## Solution

You'll need to tune this false positive away by creating a rule exclusion.

Full documentation can be found [here](https://coreruleset.org/docs/concepts/false_positives_tuning/). *Be sure to check out the examples at the bottom: they're very helpful.*

Please let us know if you need any further help with this and we can assist further.

**Comment by flexstat** [comment]
thank you for such a detailed answer. to make an exception, I need to add this expression SecRuleUpdateTargetById 941120 "!ARGS: являются не" 

am I right? or is there a more flexible solution ?

**Comment by flexstat** [comment]
> Hi @flexstat,
> 
> Firstly, it appears that you're running CRS version 3.3.2. You should strongly consider updating to the latest stable release, which is v3.3.4, as that fixes several security vulnerabilities (see [here](https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/) and [here](https://coreruleset.org/20220920/crs-version-3-3-4-and-3-2-3/) for more information.)
> 
> Secondly, have you tuned the Core Rule Set for your web application? It looks like you're running with an inbound anomaly score threshold of 5, which is not a good idea unless you have completed the full tuning process - because otherwise you are highly likely to run into false positives like the one you've reported here!
> 
> Lastly, let's look at the false positive you've reported. Unfortunately, this is an example where a CRS rule can take valid UTF-8 and its anti-evasion transformations turn that UTF-8 into rubbish. The problem is that the transformed rubbish can sometimes trigger the rule, which is the case here:
> 
> ```
> Input: являются не
> Transformation - UTF-8 to Unicode: "%u044f%u0432%u043b%u044f%u044e%u0442%u0441%u044f %u043d%u0435"
> Transformation - Decode percent-encoded string and accept Microsoft %uXXXX variant: "O2;ONBAO =5"
> ```
> 
> `;ONBAO =5` looks a bit like `onload="alert(1)"` and matches the pattern of this particular anti-XSS rule.
> ### Solution
> 
> You'll need to tune this false positive away by creating a rule exclusion.
> 
> Full documentation can be found [here](https://coreruleset.org/docs/concepts/false_positives_tuning/). _Be sure to check out the examples at the bottom: they're very helpful._
> 
> Please let us know if you need any further help with this and we can assist further.
> 
> (P.S. If it were me, I would personally be tempted to tune this away by excluding `ARGS:message` from rule 941120 for the location in question, which I'm guessing is `/mail.php`).

hi

> Hi @flexstat,
> 
> Firstly, it appears that you're running CRS version 3.3.2. You should strongly consider updating to the latest stable release, which is v3.3.4, as that fixes several security vulnerabilities (see [here](https://coreruleset.org/20220919/crs-version-3-3-3-and-3-2-2-covering-several-cves/) and [here](https://coreruleset.org/20220920/crs-version-3-3-4-and-3-2-3/) for more information.)
> 
> Secondly, have you tuned the Core Rule Set for your web application? It looks like you're running with an inbound anomaly score threshold of 5, which is not a good idea unless you have completed the full tuning process - because otherwise you are highly likely to run into false positives like the one you've reported here!
> 
> Lastly, let's look at the false positive you've reported. Unfortunately, this is an example where a CRS rule can take valid UTF-8 and its anti-evasion transformations turn that UTF-8 into rubbish. The problem is that the transformed rubbish can sometimes trigger the rule, which is the case here:
> 
> ```
> Input: являются не
> Transformation - UTF-8 to Unicode: "%u044f%u0432%u043b%u044f%u044e%u0442%u0441%u044f %u043d%u0435"
> Transformation - Decode percent-encoded string and accept Microsoft %uXXXX variant: "O2;ONBAO =5"
> ```
> 
> `;ONBAO =5` looks a bit like `onload="alert(1)"` and matches the pattern of this particular anti-XSS rule.
> ### Solution
> 
> You'll need to tune this false positive away by creating a rule exclusion.
> 
> Full documentation can be found [here](https://coreruleset.org/docs/concepts/false_positives_tuning/). _Be sure to check out the examples at the bottom: they're very helpful._
> 
> Please let us know if you need any further help with this and we can assist further.
> 
> (P.S. If it were me, I would personally be tempted to tune this away by excluding `ARGS:message` from rule 941120 for the location in question, which I'm guessing is `/mail.php`).

hello again @RedXanadu . can you help and answer my questions above ?

**Comment by RedXanadu** [comment]
Hi @flexstat,

The first step, find the offending variable. Looking at your log snippet:

``
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)[\s…\x3B]*?=[^=]' against variable `ARGS:message'…
``

we can see that the variable `ARGS:message` is causing the problem.

The offending request is a POST request, so it is very likely that `message` is a parameter in the HTTP request body. I guess this is a web mail service? So `message` probably contains the contents/body of the email. Free text input like this can cause many false positives because user input is unpredictable!

---

To tune away this false positive, we can take the approach like in our [example 3](https://coreruleset.org/docs/concepts/false_positives_tuning/#example-3-secruleupdatetargetbyid):
We wish to exclude the variable `message` from rule 941120 to prevent future false positives.

```
# CRS Rule Exclusion: 941120 - XSS Filter - Category 2: Event Handler Vector
# The "message" variable contains free text user input. UTF-8 input in
# particular is known to cause false positives with rule 941120.
SecRuleUpdateTargetById 941120 "!ARGS:message"
```

This **must** be placed **after** the `Include` directives which load the CRS.

Note: This will turn off rule 941120 for the variable `message` for _all_ locations. This is probably acceptable, but in some scenarios this is a small security risk (e.g. if `message` is used on many pages of your web application.)

---

Alternatively, if you want to restrict the exclusion only to the relevant URI (so that `message` is only excluded from rule 941120 for the location '/mail.php' and not for _all_ locations) then you could do something like our [example 7](https://coreruleset.org/docs/concepts/false_positives_tuning/#example-7-ctlruleremovetargetbyid) instead:

```
# CRS Rule Exclusion: 941120 - XSS Filter - Category 2: Event Handler Vector
# The "message" variable contains free text user input. UTF-8 input in
# particular is known to cause false positives with rule 941120.
SecRule REQUEST_URI "@beginsWith /mail.php" \
    "id:1000,\
    phase:1,\
    pass,\
    nolog,\
    ctl:ruleRemoveTargetById=941120;ARGS:message"
```

This **must** be placed **before** the `Include` directives which load the CRS.

**Comment by flexstat** [comment]
Hi @RedXanadu. Thank you ! 
can you tell me which file I should add this exception to ?



# CRS Rule Exclusion: 941120 - XSS Filter - Category 2: Event Handler Vector
# The "message" variable contains free text user input. UTF-8 input in
# particular is known to cause false positives with rule 941120.
SecRuleUpdateTargetById 941120 "!ARGS:message"

**Comment by RedXanadu** [comment]
To clarify, `message` is the variable you need to exclude from the rule.

If you examined the raw HTML request then you would see that there's a variable named `message` in there (probably in the request body) and the value of the variable `message` is the contents of the email (again, assuming this is a webmail application).

So, you need to exclude the _variable_ `message`. Doing that will prevent this false positive from occurring with _any_ future value of `message`. You're not excluding one _specific_ pattern or content like ";ONBAO =5" or "являются не".

The earlier example was literal: you would need to use
`SecRuleUpdateTargetById 941120 "!ARGS:message"`
not
`"!ARGS:ONBAO =5"`
Definitely make sure to add some comments so that you know what this exclusion is for in the future.

And to confirm, you were correct: `RESPONSE-999-EXCLUSION-RULES-AFTER` would be a valid place to put this type of rule exclusion :slightly_smiling_face:

**Comment by flexstat** [comment]
Now I understand, thank you. unfortunately, we cannot exclude a variable from the check even for certain pages, since it is not safe to tell me, is it impossible to exclude a certain text, not a variable, namely a word or phrase?

**Comment by flexstat** [comment]
> Why do you think the proposed solution is not a safe solution?

because an attacker, for example, can take advantage of the fact that this rule is disabled for the form, for example.

**Comment by dune73** [comment]
Don't overestimate this problem. You assume that CRS would be a canonical set of rules you **need** to have. In fact it's just an organically grown set of rules we think useful. 1 more or less is usually no bug deal, since you need to see it in the context of the 150 rules that do not exist and would be nice to have.

**Comment by RedXanadu** [comment]
Hi @flexstat,

I've presented several solutions so far in this thread, rule exclusions ranging from ‘slightly coarse’ to ‘fine’ to ‘very fine’.

Tuning away a false positive requires poking a hole in your web application firewall: the trick is to make the hole as small as is _practically_ possible! I believe that's been achieved here and one of the solutions above will meet your needs in a secure way: you need to pick which solution is right for you and your needs.

I'm not sure there's anything further we can do here. I'm closing this thread now, but feel free to add further comments or questions if you have any. Thanks!
