### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by leveryd** [coreruleset/coreruleset#3244]
### Describe the bug

https://github.com/coreruleset/coreruleset/blob/v3.3.0/util/regexp-assemble/regexp-942260.data

![image](https://github.com/coreruleset/coreruleset/assets/1846319/0f191e72-572e-469b-884a-86bf83849deb)

```
[\"'`]\s*?[^?\w\s=.,;)(]++\s*?[(@\"'`]*?\s*?\w+\W+\w
```

this regex comiple will result error, i think it should be

```
[\"'`]\s*?[^?\w\s=.,;)(]+\s*?[(@\"'`]*?\s*?\w+\W+\w
```

**Comment by airween** [comment]
Hi @leveryd ,

thanks for your feedback.

Sorry to say but it seems you check only the part of the whole regex. The whole generated regex is [here](https://github.com/coreruleset/coreruleset/blob/v3.3/master/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L732).

```
(?i:[\"'`]\s*?(?:(?:n(?:and|ot)|(?:x?x)?or|between|\|\||and|div|&&)\s+[\s\w]+=\s*?\w+\s*?having\s+|like(?:\s+[\s\w]+=\s*?\w+\s*?having\s+|\W*?[\"'`\d])|[^?\w\s=.,;)(]++\s*?[(@\"'`]*?\s*?\w+\W+\w|\*\s*?\w+\W+[\"'`])|(?:union\s*?(?:distinct|[(!@]*?|all)?\s*?[([]*?\s*?select|select\s+?[\[\]()\s\w\.,\"'`-]+from)\s+|\w\s+like\s+[\"'`]|find_in_set\s*?\(|like\s*?[\"'`]%)
```

Please note that we generally use this rule set for two WAF engines: mod_security2 and libmodsecurity3. Both of them can be work with PCRE and PCRE2. Our CI/CD flow checks the rule set after each PR, and many user use it - so **I'm sure if there would be any compilation issue, we would know that**.

I checked now both your sub-pattern and the whole pattern with [regex101](https://regex101.com), which allowed all patterns - there weren't any compilation issue.

I assume the tool what you use (you didn't reported what's that) is wrong.

I'm going to close this issue because there isn't any relevant nor useful information. Feel free top reopen it if you think I'm wrong.

**Comment by leveryd** [comment]
I see, `++` means `possessive`, and `+` means `greedy`

![image](https://github.com/coreruleset/coreruleset/assets/1846319/460a84c4-912a-40fe-835e-24625eee6cb1)

![image](https://github.com/coreruleset/coreruleset/assets/1846319/7a708872-37f0-40cd-a0ae-c55fd4f4e45b)

And some language or library does not support `possessive` mode, like python3

```
>>> import re
>>> re.compile("""[\"'`]\s*?[^?\w\s=.,;)(]++\s*?[(@\"'`]*?\s*?\w+\W+\w""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 619, in _parse
    source.tell() - here + len(this))
sre_constants.error: multiple repeat at position 24
>>> re.compile("""[\"'`]\s*?[^?\w\s=.,;)(]+\s*?[(@\"'`]*?\s*?\w+\W+\w""")
re.compile('["\'`]\\s*?[^?\\w\\s=.,;)(]+\\s*?[(@"\'`]*?\\s*?\\w+\\W+\\w')
>>> 
```

What is `possessive`、`greedy`, we can refer https://stackoverflow.com/questions/5319840/greedy-vs-reluctant-vs-possessive-qualifiers. In simple word,  `possessive` has no backtrace.

**Comment by airween** [comment]
> And some language or library does not support `possessive` mode, like python3

As I wrote above, our main target (in terms of regular expression engines) is PCRE and PCRE2.

Python3 is definitely out of our scope.

We'd be happy if all our regexes worked with RE2 engine, which (as I know) also doesn't support possessive repeats - so maybe it's worth checking our regexes.

But in fact, all expressions are valid for both PCRE and PCRE2.

**Comment by theseion** [comment]
> But in fact, all expressions are valid for both PCRE and PCRE2.

And RE2 now as well ;)
