### ISSUE TITLE
"MULTIPART_PART_HEADERS" Header issue in REQUEST-922-MULTIPART-ATTACK.conf 

### ISSUE THREAD

**Issue by shivapal98** [coreruleset/coreruleset#3270]
I got error in file AH00526: Syntax error on line 43 of /etc/modsecurity/rules/REQUEST-922-MULTIPART-ATTACK.conf:
I fixed my file

**Comment by shivapalsingh** [comment]
I got error in file AH00526: Syntax error on line 43 of /etc/modsecurity/rules/REQUEST-922-MULTIPART-ATTACK.conf:
I fixed my file

**Comment by shivapalsingh** [comment]
# ------------------------------------------------------------------------
# OWASP ModSecurity Core Rule Set ver.4.0.0-rc1
# Copyright (c) 2006-2020 Trustwave and contributors. All rights reserved.
# Copyright (c) 2021-2022 Core Rule Set project. All rights reserved.
#
# The OWASP ModSecurity Core Rule Set is distributed under
# Apache Software License (ASL) version 2
# Please see the enclosed LICENSE file for full details.
# ------------------------------------------------------------------------

#
# -= Paranoia Level 0 (empty) =- (apply unconditionally)
#

# This file is to address the 3UWMWA6W vulnerability.
# It requires ModSecurity version 2.9.6 or 3.0.8 (or an updated version with backports
# of the security fixes in these versions) or a compatible engine supporting these changes.
#
# If you cannot upgrade ModSecurity, this file will cause ModSecurity to fail to start.
# In that case, you can temporarily delete this file. However, you will be missing
# protection from these rules. Therefore, we recommend upgrading your engine instead.

# The rules in this file will be part of the 920 / 921 in the future.

# Only allow specific charsets when using "_charset_"
# Note: this is in phase:2 because these are headers that come in the body
SecRule ARGS:_charset_ "!@within |%{tx.allowed_request_content_type_charset}|" \
    "id:922100,\
    phase:2,\
    block,\
    t:none,\
    msg:'Multipart content type global _charset_ definition is not allowed by policy',\
    logdata:'Matched Data: %{ARGS._charset_}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-multipart-header',\
    tag:'OWASP_CRS',\
    tag:'capec/1000/255/153',\
    tag:'paranoia-level/1',\
    ver:'OWASP_CRS/4.0.0-rc1',\
    severity:'CRITICAL',\
    chain"
    SecRule ARGS:_charset_ "!@rx (?i)^((?!(utf-8|iso-8859-15|windows-1252)).)*$" \
        "setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

# Only allow specific charsets same as Rule 920600
# Note: this is in phase:2 because these are headers that come in the body
SecRule REQUEST_HEADERS:Content-Type "@rx (?i)^multipart/form-data;.*\bcharset=(?!(utf-8|iso-8859-15|windows-1252))" \
    "id:922110,\
    phase:2,\
    block,\
    t:none,\
    msg:'Illegal MIME Multipart Header content-type: charset parameter',\
    logdata:'Matched Data: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-protocol',\
    tag:'OWASP_CRS',\
    tag:'capec/272/220',\
    tag:'paranoia-level/1',\
    ver:'OWASP_CRS/4.0.0-rc1',\
    severity:'CRITICAL',\
    chain"
    SecRule REQUEST_HEADERS:Content-Type "!@rx (?i)^multipart/form-data;.*\bcharset=(utf-8|iso-8859-15|windows-1252)" \
        "setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

# Content-Transfer-Encoding was deprecated by rfc7578 in 2015 and should not be used (see: https://www.rfc-editor.org/rfc/rfc7578#section-4.7)
# Note: this is in phase:2 because these are headers that come in the body
SecRule REQUEST_HEADERS:Content-Type "@contains (?i)content-transfer-encoding:" \
    "id:922120,\
    phase:2,\
    block,\
    t:none,\
    msg:'Content-Transfer-Encoding was deprecated by rfc7578 in 2015 and should not be used',\
    logdata:'Matched Data: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-deprecated-header',\
    tag:'OWASP_CRS',\
    tag:'capec/272/220',\
    tag:'paranoia-level/1',\
    ver:'OWASP_CRS/4.0.0-rc1',\
    severity:'CRITICAL',\
    chain"
    SecRule REQUEST_HEADERS:Content-Type "!@contains (?i)content-transfer-encoding:(?:\s+|$)" \
        "setvar:'tx.inbound_anomaly_score_pl1=+%{tx.critical_anomaly_score}'"

**Comment by shivapalsingh** [comment]
Hiello @azurit When I restarted Apache, I received an error, and it is displayed in the REQUEST-922-MULTIPART-ATTACK.conf file, which I will provide below for your reference.
![Screenshot from 2023-07-28 00-36-37](https://github.com/coreruleset/coreruleset/assets/33564543/ac1957e6-b0d0-42ca-9b41-2976be2993a1)

**Comment by airween** [comment]
> Hiello @azurit When I restarted Apache, I received an error, and it is displayed in the REQUEST-922-MULTIPART-ATTACK.conf file, which I will provide below for your reference. ![Screenshot from 2023-07-28 00-36-37](https://user-images.githubusercontent.com/33564543/256640514-ac1957e6-b0d0-42ca-9b41-2976be2993a1.png)

Hi @shivapalsingh,

there are [several](https://github.com/coreruleset/coreruleset/issues/3129) [other](https://github.com/coreruleset/coreruleset/issues/3069) [issues](https://github.com/coreruleset/coreruleset/issues/2795) like [your](https://github.com/coreruleset/coreruleset/issues/2776), please choose one for the solution.

At least, please take a look to the CRS [FAQ](https://coreruleset.org/faq/#multipart).
