### ISSUE TITLE
I got this error while installing

### ISSUE THREAD

**Issue by abhijith-neork** [coreruleset/coreruleset#3406]
AH00526: Syntax error on line 43 of /etc/apache2/modsecurity-crs/coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf:
Error creating rule: Unknown variable: &MULTIPART_PART_HEADERS

**Comment by airween** [comment]
Hi @abhijith-neork,

unfortunately you haven't followed any of our [issue templates](https://github.com/coreruleset/coreruleset/issues/new/choose), but I'm sure you have an old version of ModSecurity for the used CRS. Since 3.3.4 CRS needs ModSecurity 2.9.6 or libmodsecurity3 3.0.8 at least.

Please read the announcement [here](https://github.com/coreruleset/coreruleset/releases/tag/v3.3.4).

I'm closing this issue.
