### ISSUE TITLE
Wordpress saving fails even with crs_exclusions_wordpress set

### ISSUE THREAD

**Issue by catharsis71** [coreruleset/coreruleset#3459]
### Description

I added the following after noting that modsecurity blocks all saving of Wordpress edits:

```SecAction "id:900130,phase:1,nolog,pass,t:none,setvar:tx.crs_exclusions_wordpress=1"```

however, all attempts to save are still blocked

### How to reproduce the misbehavior (-> curl call)

Edit Wordpress page, attempt to save

### Logs

too large, see attached [log.txt](https://github.com/coreruleset/coreruleset/files/13846573/log.txt)

### Your Environment

* CRS version:  3.3.2-1
* Paranoia level setting:  1
* ModSecurity version:  3.0.6-1
* Web Server and version or cloud provider / CDN:  Apache 2.4.52-1ubuntu4.7
* Operating System and version:  Ubuntu 22.04.3 LTS

### Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by M4tteoP** [comment]
Hi @catharsis71,

You are facing FPs triggered only by one rule (for a total of 54 times). it is the `942100` that relies on Libinjection for detection. It is a third-party library that we are leveraging for XSS/SQLi detections. The most we can do in that case is about writing exclusion rules disabling the rule to check specific parameters or even completely for specific paths.

A similar report has been https://github.com/coreruleset/coreruleset/issues/1511, where an external theme was the root cause of the generated FPs, are you using any of them?

**Comment by catharsis71** [comment]
Thank you for the information. 

I was using a third-party theme but I switched to one of the official themes "Twenty Twenty-Two" and also disabled all plugins and the behavior appears to be the same.

I have /wp-admin/ protected via Cloudflare Access so I tried this and it seemed to work:

```SecRule &REQUEST_COOKIES_NAMES:CF_Authorization "@eq 1" id:900131,ctl:ruleRemoveById=942100,nolog```

(I'm pretty sure Cloudflare won't pass along a spoofed CF_Authorization cookie so I think this is safe)

Seems to work okay so far... I guess this is the best I can do for now?

**Comment by catharsis71** [comment]
after identifying additional save failures, I had to do 941180, 932105, 941101, and 941160 as well

```SecRule &REQUEST_COOKIES_NAMES:CF_Authorization "@eq 1" id:900131,ctl:ruleRemoveById=942100,ctl:ruleRemoveById=941180,ctl:ruleRemoveById=932105,ctl:ruleRemoveById=941101,ctl:ruleRemoveById=941160,nolog```

**Comment by M4tteoP** [comment]
As far as I know, running the CRS with WordPress comes with quite some exclusion rules needed, so I think that it is the way to go. @azurit can you confirm that?

`941101` and `941100` are Libinjection rules, while the others are plain CRS ones. We might take a look at each match to see if there are false positives that can be fixed upstream, but looking at the request, WordPress is sending a JSON with lots of code-like strings, so I'm expecting rules to be triggered around XSS/RCE. 

About the exclusion rule, depending on your security posture (maybe you are okay with just Cloudflare Access for /wp-admin/), you might want to fine-tune each a bit more each exclusion removing only specific args that are getting matched or adding a chained rule to the one you wrote in order to match only the `site-editor.php` path.

**Comment by azurit** [comment]
As @M4tteoP already stated, running WordPress with CRS requires lots of exclusion rules but it's possible.

**Comment by catharsis71** [comment]
> quite some exclusion rules needed

I don't suppose someone already made a list?  Seems like something that should exist although I guess it might depend on theme/plugins used

here's what I have so far

942100
941180
932105
941101
941160
941100

**Comment by azurit** [comment]
@catharsis71 Unfortunately, this isn't as easy as it may seems. WordPress has tons of plugins and themes. To get you into a perspective - i'm running a webhosting services where CRS is enabled by default (on PL1). To make it all work, we already created more than 350 exclusion rules and more are added every day.

I can share some of them, and help you to run CRS with WP, if you can provide me with an audit log.

**Comment by azurit** [comment]
@catharsis71 Ping.
