### ISSUE TITLE
False positive for Adobe Reader submissions

### ISSUE THREAD

**Issue by MVS** [coreruleset/coreruleset#3591]
### Description
When a PDF form in Adobe Reader submits directly to the server, it uses the Content-type "application/pdf". This is blocked by the CRS (rule 920420).

### How to reproduce the misbehavior (-> curl call)
This works:
`curl -X POST http://localhost/ -H "Content-type: application/xml"`
But this does not:
`curl -X POST http://localhost/ -H "Content-type: application/pdf"`

### Your Environment

* CRS version (e.g., v3.3.4): 3.0.2 (cPanel)
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6): 2.9.7
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): Apache 2.4.58 (cPanel)
* Operating System and version: CloudLinux 7.9.0

### Confirmation

- [x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theseion** [comment]
Hi @MVS, we block `application/pdf` by design. If this is something you need for yourself, you can configure the allowed request content types in rule `900220` in the crs-setup.conf (https://github.com/coreruleset/coreruleset/blob/0bd51ff806c68e2a54c4d60ca13f731c5355696d/crs-setup.conf.example#L422).

**Comment by MVS** [comment]
Understood, thanks.
