### ISSUE TITLE
Block AI scraping bots

### ISSUE THREAD

**Issue by highpingblorg** [coreruleset/coreruleset#3850]
### Motivation

In the past few months, we have seen AI scraping bots become more and more prevalent, especially ClaudeBot. Personally, I've seen it do as much as 10K requests in 24 hours, with some reporting as many as [2 million requests in 7 days](https://www.reddit.com/r/Anthropic/comments/1c8tu5u/comment/l17430p/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). Since regular anti scraping/crawling bots rules are implemented in CRS, it isn't such a far fetched idea to implement one specifically for AI scrapers.

This would:
1. Reduce the amount of traffic being actually processed
2. Allow end-users to prevent AI bots from stealing their data
3. Prevent attackers from using AI scraping bots to automate their enumeration and pentesting efforts

### Proposed solution

Add a `SecRule` to `REQUEST-913-SCANNER-DETECTION.conf`, along side a `.data` file containing the User-agents of the AI scraping bots.

The rule should be separate rule to differentiate from the other non-AI crawler rule trigger messages. 

### Alternatives

An alternative solution would be adding to the `robots.txt` file to disallow these bots. Unfortunately, it has been seen that they ignore the `robots.txt` file.

**Comment by fzipi** [comment]
Hi @highpingblorg. Sounds reasonable.

Do you have a list for such bots to start with?

**Comment by fzipi** [comment]
Amazing... so... can you provide a PR?

**Comment by highpingblorg** [comment]
Done  #3852

**Comment by RedXanadu** [comment]
We previously made the decision as a project to move away from and to scale back our user agent-based anti-bot detection rules (see #3236). We removed several rules and user agents lists from core CRS at that time.

The idea was that anti-bot and user agent-based bot and scraper detection would make an excellent case for a [plugin](https://github.com/coreruleset/plugin-registry). I think that an anti-AI bot plugin would be a welcome addition to the current roster of plugins.

If there is call to reverse that stance and to start re-adding user agent rules into core CRS again then we should discuss that at a team meeting. Specifically: has the situation changed since the previous decision? Have the problems from last time now been resolved? Etc.

**Comment by highpingblorg** [comment]
If the decision has been made that CRS v4 will perform these kinds of actions via plugins, then this feature can be applied to CRS v3, since that version still gets a lot of traction.

For CRS v4 these changes will just be added to the plugin system, that way both "major" versions are up to date and both versions adhere to their implementation of this action.
